### ISSUE TITLE
Molden printing

### ISSUE THREAD

**Issue by SebWouters** [sunqm/pyscf#10]
Hi,

With the following code:

    mol = gto.Mole()
    mol.atom = '''
       O  0.000000000  0.00000000  0.000000000;
       H  0.790689766  0.00000000  0.612217330;
       H -0.790689766  0.00000000  0.612217330
               '''
    mol.basis = '6-31g'
    mol.symmetry = 1
    mol.charge = 0
    mol.spin = 0 #2*S; multiplicity-1
    mol.build()

    mf = scf.RHF(mol)
    mf.verbose = 0
    mf.scf()
    
    with open('H2Omo.txt', 'w') as f1:
        molden.header(mol, f1)
        molden.orbital_coeff(mf.mol, f1, mf.mo_coeff, ene=mf.mo_energy, occ=mf.mo_occ)
    
    c_loc_orth = lo.orth_ao(mol, 'meta_lowdin')
    
    with open('H2Oloc.txt', 'w') as f2:
        molden.header(mol, f2)
        molden.orbital_coeff(mf.mol, f2, c_loc_orth)

I get the error:

    Traceback (most recent call last):
      File "test.py", line 28, in <module>
        molden.header(mol, f1)
      File "/home/seba/pyscf/tools/molden.py", line 26, in header
        for b in mol.basis[mol.atom_symbol(ia)]:
    TypeError: string indices must be integers, not str

**Comment by sunqm** [comment]
It is fixed in lastest updates.
