### ISSUE TITLE
pbc.dft.test.test_ks_noimport.py does not converge

### ISSUE THREAD

**Issue by pulkin** [sunqm/pyscf#103]
The standalone test I proposed suffers from convergence issues (dev branch).
```
init E= -10.733248177868
HOMO = -1.18516728756  LUMO = -0.944279011822
cycle= 1 E= 32.8042868359773  delta_E= 43.5  |g|= 15.6  |ddm|= 41.2
HOMO = 7.70665889932  LUMO = 10.3768737466
cycle= 2 E= -4.69630753356  delta_E= -37.5  |g|= 5.47  |ddm|= 48.6
HOMO = -0.456270745914  LUMO = -0.1322822107
cycle= 3 E= 27.5474545612495  delta_E= 32.2  |g|= 32.8  |ddm|= 46.6
HOMO = -0.764295757509  LUMO = -0.429388018793
cycle= 4 E= 30.5860020151835  delta_E= 3.04  |g|= 25.4  |ddm|= 3.84
HOMO = -0.487388317343  LUMO = -0.154586004315
cycle= 5 E= 28.2774392675314  delta_E= -2.31  |g|= 30.9  |ddm|= 3.17
HOMO = 0.238808596413  LUMO = 0.238808596413

WARN: HOMO 0.238808596413 == LUMO 0.238808596413

cycle= 6 E= -6.53051694704711  delta_E= -34.8  |g|= 29.2  |ddm|= 29.1
HOMO = 0.20597970858  LUMO = 0.20597970858

WARN: HOMO 0.20597970858 == LUMO 0.20597970858

cycle= 7 E= -3.94739720390383  delta_E= 2.58  |g|= 35.6  |ddm|= 5.29
HOMO = 0.236194999194  LUMO = 0.236194999194

WARN: HOMO 0.236194999194 == LUMO 0.236194999194
```
and so on. As far as I remember it was OK previously.

**Comment by pulkin** [comment]
It seems like it is my fork which fails. Can anyone test it with the dev branch?

**Comment by sunqm** [comment]
This is the output of dev branch

Set gradient conv threshold to 3.16228e-05
init E= -12.3634534045821
HOMO = -0.279550299825  LUMO = -0.0395613956105
cycle= 1 E= -12.2900356079511  delta_E= 0.0734  |g|=  1.3  |ddm|= 8.34
HOMO = 0.0341748864163  LUMO = 0.0574059736496
cycle= 2 E= -12.2333737774339  delta_E= 0.0567  |g|= 1.86  |ddm|= 4.75
HOMO = -0.0989398356626  LUMO = 0.0562117304554
cycle= 3 E= -12.3462938863174  delta_E= -0.113  |g|= 0.036  |ddm|= 2.92
HOMO = -0.100618760021  LUMO = 0.0507205219818
cycle= 4 E= -12.3463363294384  delta_E= -4.24e-05  |g|= 0.00187  |ddm|= 0.0636
HOMO = -0.100762757321  LUMO = 0.0506414301057
cycle= 5 E= -12.346336437466  delta_E= -1.08e-07  |g|= 5.29e-05  |ddm|= 0.00278
HOMO = -0.100768365629  LUMO = 0.0506397754779
cycle= 6 E= -12.3463364375776  delta_E= -1.12e-10  |g|= 3.67e-06  |ddm|= 0.000105
HOMO = -0.100769306088  LUMO = 0.0506395786168
Extra cycle  E= -12.3463364375772  delta_E= 3.38e-13  |g|= 3.67e-06  |ddm|= 1.37e-05
converged SCF energy = -12.3463364375772
Maximum deviation: 0.049841629732  Hartree
