### ISSUE TITLE
Density Matrix can't be calculated

### ISSUE THREAD

**Issue by gmwang18** [sunqm/pyscf#105]
Code:
from pyscf import gto, scf, cc

mole = gto.Mole()
mole.atom = 'O 0 0 0'
mole.basis = 'ccpvdz'
mole.spin = 2
mole.verbose = 3
mole.build()
mf=scf.UHF(mole)
mf.kernel()
mycc=cc.UCCSD(mf)
dm1 = mycc.make_rdm1()
dm2 = mycc.make_rdm2()
mycc.kernel()

Error:
converged SCF energy = -74.792166058284
Traceback (most recent call last):
  File "o.py", line 12, in <module>
    dm1 = mycc.make_rdm1()
  File "/home/gwang18/software/pyscf/pyscf/cc/ccsd.py", line 604, in make_rdm1
    if l1 is None: l1, l2 = self.solve_lambda(t1, t2)
  File "/home/gwang18/software/pyscf/pyscf/cc/ccsd.py", line 594, in solve_lambda
    verbose=self.verbose)
  File "/home/gwang18/software/pyscf/pyscf/cc/ccsd_lambda.py", line 33, in kernel
    nocc, nvir = t1.shape
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by tberkel** [comment]
You have to run the CCSD before making the RDMs, i.e. call mycc.kernel() before mycc.make_rdm1().  However, this will also fail, because (as far as I know), pyscf does not yet implement the unrestricted lambda equations (needed for RDMs).

**Comment by sunqm** [comment]
The dev branch now has the UCCSD 1pdm and 2pdm code.  The current implementation is not optimized for performance.  The optimization will be done later.
