### ISSUE TITLE
UCCSD seems not converging for a successful running

### ISSUE THREAD

**Issue by gmwang18** [sunqm/pyscf#107]
PYSCF gives different CCSD energies for the same code with multiple running.
I have a state of Carbon atom C(0) 2s2_2p_5s.
My code is working(running smoothly with SCF and CCSD energy given). 
But I find pyscf for every running gives me different CCSD energy.
I am quite confused, is the CCSD energy not converging or any bug in it? 
```python
#! /usr/bin/env python

from pyscf import scf,gto,cc

mol = gto.Mole()
mol.atom = ''' C 0.0 0.0 0.0 '''
mol.basis = {'C': 'unc-ccpv5z'}#gto.load(basfile,'C')}
mol.ecp = {'C': 'sbkjc'}
mol.symmetry = 'D2h'
mol.spin = 0
mol.charge = 0
mol.build()

hf = scf.UHF(mol)
hf.irrep_nelec = {
'Ag' : (2,1),
'B3u': (0,1),
'B2u': (0,0),
'B1g': (0,0),
'B1u': (0,0),
'B2g': (0,0),
'B3g': (0,0),
'Au' : (0,0)
}

hf.kernel()

#Wanted state: C(0) 2s2_2p_5s(1P)
hf.analyze()
mo0 = hf.mo_coeff
occ = hf.mo_occ
occ[0][1]  = 0
occ[0][12] = 1
hf = scf.UHF(mol)
hf.irrep_nelec = {
'Ag' : (2,1),
'B3u': (0,1),
'B2u': (0,0),
'B1g': (0,0),
'B1u': (0,0),
'B2g': (0,0),
'B3g': (0,0),
'Au' : (0,0)
}
dm_u = hf.make_rdm1(mo0, occ)
hf = scf.addons.mom_occ(hf, mo0, occ)
hf.scf(dm_u)
hf.analyze()

mycc = cc.UCCSD(hf)
mycc.kernel()
```

**Comment by aannabe** [comment]
I second this. I ran the above code 3 times commenting out hf.analyze. All results have different correlation energies:
```
converged SCF energy = -4.93227865719341
Overwrite attributes  get_occ  of <class 'pyscf.scf.uhf_symm.UHF'>
converged SCF energy = -4.67717523866414
E(CCSD) = -5.011890265796444  E_corr = -0.3347150271323045
```
```
converged SCF energy = -4.93227865719341
Overwrite attributes  get_occ  of <class 'pyscf.scf.uhf_symm.UHF'>
converged SCF energy = -4.67717523866414
E(CCSD) = -4.967327818498367  E_corr = -0.2901525798342293
```
```
converged SCF energy = -4.93227865719341
Overwrite attributes  get_occ  of <class 'pyscf.scf.uhf_symm.UHF'>
converged SCF energy = -4.67717523866413
E(CCSD) = -4.998752720828064  E_corr = -0.3215774821639335
```

**Comment by sunqm** [comment]
Shortly, the UCCSD does not converge.  I'm not sure why unc-ccpv5z is difficult to converge but other basis looks fine.  A workaround is to increase diis space eg

mycc.diis_space = 12

You'll get the correlation ~0.3 hartree.  This is too large.  I suspect it corresponds to a spin-flip solution.

Another workaround is to project the amplitudes from a converged solution.  Assuming ccpv5z calculation converged, you can first compute the orbital transformation c
```
s12 = gto.intor_cross('int1e_ovlp', mf_5z.mol, mf_unc5z.mol)
vorb_a_5z = mf_5z.mo_coeff[0][:,mf_5z.mo_occ[0]==0]
vorb_b_5z = mf_5z.mo_coeff[1][:,mf_5z.mo_occ[1]==0]
vorb_a_unc5z = mf_unc5z.mo_coeff[0][:,mf_unc5z.mo_occ[0]==0]
vorb_b_unc5z = mf_unc5z.mo_coeff[1][:,mf_unc5z.mo_occ[1]==0]
c_a = vorb_a_5z.T.dot(s12).dot(vorb_a_unc5z)
c_b = vorb_a_5z.T.dot(s12).dot(vorb_a_unc5z)
```
Then project the ccpv5z UCCSD t1 t2 amplitudes to unc-ccpv5z UCCSD t1 t2 and pass them to the UCCSD kernel function
```
t1a = numpy.einsum('ia,ac->ic', uccsd_5z.t1[0], c_a)
t1b = numpy.einsum('ia,ac->ic', uccsd_5z.t1[1], c_b)
t2aa = numpy.einsum('ijab,ac,bd->ijcd', uccsd_5z.t2[0], c_a, c_a)
t2ab = numpy.einsum('ijab,ac,bd->ijcd', uccsd_5z.t2[1], c_a, c_b)
t2bb = numpy.einsum('ijab,ac,bd->ijcd', uccsd_5z.t2[2], c_b, c_b)
...
uccsd_unc5z.kernel([t1a,t1b], [t2aa,t2ab,t2bb])
```

**Comment by jdmcclain47** [comment]
Also as an aside to anyone that is unaware, setting the verbose option for any of the methods to their non-default value can help in giving more information on things such as timing and convergence.

Here you can set the verbose option (the higher the number the more verbose the output)
`mycc.verbose = 4`
after mycc initialization to see the convergence.

**Comment by aannabe** [comment]
Thank you for your answers.
