### ISSUE TITLE
Operators (|z|) and (|zz|)

### ISSUE THREAD

**Issue by SebWouters** [sunqm/pyscf#11]
Hi Qiming,

In http://sunqm.net/pyscf/gto.html#module-pyscf.gto.moleintor you describe that you have the operators:
“cint1e_z_sph”     spheric     ( | z | )
“cint1e_zz_sph”     spheric     ( | z z | )

In principle, as atoms move away from the origin along the z-axis, the values (i|z|i) should change in magnitude proportional to the shift along the z-axis?

In AO for the H-chain

    BOHR = 0.52917721092
    separation = 2.0
    num_atoms = 12
    z_co = BOHR*separation*np.arange(0.0,num_atoms-0.5,1.0)
    z_co = z_co - np.average(z_co)
    print "z_co =",z_co
    mol = gto.Mole()
    mol.atom = []
    for zco in z_co:
        mol.atom.append(('H', (0, 0, zco)))
    mol.basis = 'sto-3g'
    mol.symmetry = 1
    mol.charge = 0
    mol.spin = 0 #2*S; multiplicity-1
    mol.build()

you / pyscf / cint get for (|z|):

    [[  6.26596548e-16  -4.62777691e-01  -1.96265900e-01  -3.75938850e-02
       -3.85043869e-03  -2.15980014e-04  -6.23600664e-06  -9.00599343e-08
       -6.49351112e-10  -2.34589262e-12  -4.26003046e-15  -3.89781041e-18]
     [  4.62777691e-01   0.00000000e+00  -4.62777691e-01  -1.96265900e-01
       -3.75938850e-02  -3.85043869e-03  -2.15980014e-04  -6.23600664e-06
       -9.00599343e-08  -6.49351112e-10  -2.34589262e-12  -4.26003046e-15]
     [  1.96265900e-01   4.62777691e-01  -9.00445191e-17  -4.62777691e-01
       -1.96265900e-01  -3.75938850e-02  -3.85043869e-03  -2.15980014e-04
       -6.23600664e-06  -9.00599343e-08  -6.49351112e-10  -2.34589262e-12]
     [  3.75938850e-02   1.96265900e-01   4.62777691e-01   3.35579166e-17
       -4.62777691e-01  -1.96265900e-01  -3.75938850e-02  -3.85043869e-03
       -2.15980014e-04  -6.23600664e-06  -9.00599343e-08  -6.49351112e-10]
     [  3.85043869e-03   3.75938850e-02   1.96265900e-01   4.62777691e-01
       -2.73560224e-17  -4.62777691e-01  -1.96265900e-01  -3.75938850e-02
       -3.85043869e-03  -2.15980014e-04  -6.23600664e-06  -9.00599343e-08]
     [  2.15980014e-04   3.85043869e-03   3.75938850e-02   1.96265900e-01
        4.62777691e-01   0.00000000e+00  -4.62777691e-01  -1.96265900e-01
       -3.75938850e-02  -3.85043869e-03  -2.15980014e-04  -6.23600664e-06]
     [  6.23600664e-06   2.15980014e-04   3.85043869e-03   3.75938850e-02
        1.96265900e-01   4.62777691e-01   0.00000000e+00  -4.62777691e-01
       -1.96265900e-01  -3.75938850e-02  -3.85043869e-03  -2.15980014e-04]
     [  9.00599343e-08   6.23600664e-06   2.15980014e-04   3.85043869e-03
        3.75938850e-02   1.96265900e-01   4.62777691e-01   2.73560224e-17
       -4.62777691e-01  -1.96265900e-01  -3.75938850e-02  -3.85043869e-03]
     [  6.49351112e-10   9.00599343e-08   6.23600664e-06   2.15980014e-04
        3.85043869e-03   3.75938850e-02   1.96265900e-01   4.62777691e-01
       -3.35579166e-17  -4.62777691e-01  -1.96265900e-01  -3.75938850e-02]
     [  2.34589262e-12   6.49351112e-10   9.00599343e-08   6.23600664e-06
        2.15980014e-04   3.85043869e-03   3.75938850e-02   1.96265900e-01
        4.62777691e-01  -4.44226650e-16  -4.62777691e-01  -1.96265900e-01]
     [  4.26003046e-15   2.34589262e-12   6.49351112e-10   9.00599343e-08
        6.23600664e-06   2.15980014e-04   3.85043869e-03   3.75938850e-02
        1.96265900e-01   4.62777691e-01   0.00000000e+00  -4.62777691e-01]
     [  3.89781041e-18   4.26003046e-15   2.34589262e-12   6.49351112e-10
        9.00599343e-08   6.23600664e-06   2.15980014e-04   3.85043869e-03
        3.75938850e-02   1.96265900e-01   4.62777691e-01  -6.26596548e-16]]

and for (|zz|)

    [[  6.49524230e-01   9.30064857e-01   5.61017715e-01   1.38267394e-01
        1.71577527e-02   1.14834023e-03   3.89739177e-05   6.49494289e-07
        5.31499604e-09   2.14989495e-11   4.32310263e-14   4.34005444e-17]
     [  9.30064857e-01   6.49524230e-01   9.30064857e-01   5.61017715e-01
        1.38267394e-01   1.71577527e-02   1.14834023e-03   3.89739177e-05
        6.49494289e-07   5.31499604e-09   2.14989495e-11   4.32310263e-14]
     [  5.61017715e-01   9.30064857e-01   6.49524230e-01   9.30064857e-01
        5.61017715e-01   1.38267394e-01   1.71577527e-02   1.14834023e-03
        3.89739177e-05   6.49494289e-07   5.31499604e-09   2.14989495e-11]
     [  1.38267394e-01   5.61017715e-01   9.30064857e-01   6.49524230e-01
        9.30064857e-01   5.61017715e-01   1.38267394e-01   1.71577527e-02
        1.14834023e-03   3.89739177e-05   6.49494289e-07   5.31499604e-09]
     [  1.71577527e-02   1.38267394e-01   5.61017715e-01   9.30064857e-01
        6.49524230e-01   9.30064857e-01   5.61017715e-01   1.38267394e-01
        1.71577527e-02   1.14834023e-03   3.89739177e-05   6.49494289e-07]
     [  1.14834023e-03   1.71577527e-02   1.38267394e-01   5.61017715e-01
        9.30064857e-01   6.49524230e-01   9.30064857e-01   5.61017715e-01
        1.38267394e-01   1.71577527e-02   1.14834023e-03   3.89739177e-05]
     [  3.89739177e-05   1.14834023e-03   1.71577527e-02   1.38267394e-01
        5.61017715e-01   9.30064857e-01   6.49524230e-01   9.30064857e-01
        5.61017715e-01   1.38267394e-01   1.71577527e-02   1.14834023e-03]
     [  6.49494289e-07   3.89739177e-05   1.14834023e-03   1.71577527e-02
        1.38267394e-01   5.61017715e-01   9.30064857e-01   6.49524230e-01
        9.30064857e-01   5.61017715e-01   1.38267394e-01   1.71577527e-02]
     [  5.31499604e-09   6.49494289e-07   3.89739177e-05   1.14834023e-03
        1.71577527e-02   1.38267394e-01   5.61017715e-01   9.30064857e-01
        6.49524230e-01   9.30064857e-01   5.61017715e-01   1.38267394e-01]
     [  2.14989495e-11   5.31499604e-09   6.49494289e-07   3.89739177e-05
        1.14834023e-03   1.71577527e-02   1.38267394e-01   5.61017715e-01
        9.30064857e-01   6.49524230e-01   9.30064857e-01   5.61017715e-01]
     [  4.32310263e-14   2.14989495e-11   5.31499604e-09   6.49494289e-07
        3.89739177e-05   1.14834023e-03   1.71577527e-02   1.38267394e-01
        5.61017715e-01   9.30064857e-01   6.49524230e-01   9.30064857e-01]
     [  4.34005444e-17   4.32310263e-14   2.14989495e-11   5.31499604e-09
        6.49494289e-07   3.89739177e-05   1.14834023e-03   1.71577527e-02
        1.38267394e-01   5.61017715e-01   9.30064857e-01   6.49524230e-01]]

while I get for (|z|) and (|zz|):

    ( 0 | z | 0 ) = -10.999999899787800572426
    ( 0 | z | 1 ) = -4.6277769121416882924791
    ( 0 | z | 2 ) = -0.88319654823480719940676
    ( 0 | z | 3 ) = -0.10025036004989190674408
    ( 0 | z | 4 ) = -0.00673826769913168314302121
    ( 0 | z | 5 ) = -0.000259176017145982943469529
    ( 0 | z | 6 ) = -5.19667220338388105880601e-06
    ( 0 | z | 7 ) = -5.14628196118686697135586e-08
    ( 0 | z | 8 ) = -2.43506666895108163200548e-10
    ( 0 | z | 9 ) = -5.21309471544019031202246e-13
    ( 0 | z | 10 ) = -4.2600304552972045679068e-16
    ( 0 | z | 11 ) = 2.24207754291970731347797e-44
    ( 1 | z | 0 ) = -4.6277769121416882924791
    ( 1 | z | 1 ) = -8.99999991800819998388761
    ( 1 | z | 2 ) = -3.70222152971335027871191
    ( 1 | z | 3 ) = -0.6869306486270722045262
    ( 1 | z | 4 ) = -0.0751877700374189439358474
    ( 1 | z | 5 ) = -0.00481304835652263032080844
    ( 1 | z | 6 ) = -0.000172784011430655322751407
    ( 1 | z | 7 ) = -3.11800332203032846587702e-06
    ( 1 | z | 8 ) = -2.57314098059343348567793e-08
    ( 1 | z | 9 ) = -8.1168888965036071633112e-11
    ( 1 | z | 10 ) = -2.40741243048404481631997e-35
    ( 1 | z | 11 ) = 4.2600304552972045679068e-16
    ( 2 | z | 0 ) = -0.88319654823480719940676
    ( 2 | z | 1 ) = -3.70222152971335027871191
    ( 2 | z | 2 ) = -6.99999993622859939534919
    ( 2 | z | 3 ) = -2.77666614728501315312315
    ( 2 | z | 4 ) = -0.490664749019337265156793
    ( 2 | z | 5 ) = -0.0501251800249459603109337
    ( 2 | z | 6 ) = -0.00288782901391357836595741
    ( 2 | z | 7 ) = -8.63920057153276613757034e-05
    ( 2 | z | 8 ) = -1.03933444067677608470626e-06
    ( 2 | z | 9 ) = -1.61558713389263217748322e-27
    ( 2 | z | 10 ) = 8.1168888965036071633112e-11
    ( 2 | z | 11 ) = 5.21309471544019031202246e-13
    ( 3 | z | 0 ) = -0.10025036004989190674408
    ( 3 | z | 1 ) = -0.6869306486270722045262
    ( 3 | z | 2 ) = -2.77666614728501315312315
    ( 3 | z | 3 ) = -4.99999995444900058316762
    ( 3 | z | 4 ) = -1.85111076485667558344517
    ( 3 | z | 5 ) = -0.294398849411602325787385
    ( 3 | z | 6 ) = -0.0250625900124729766860199
    ( 3 | z | 7 ) = -0.000962609671304526085845732
    ( 3 | z | 8 ) = 5.29395592033937711917702e-22
    ( 3 | z | 9 ) = 1.03933444067677608470626e-06
    ( 3 | z | 10 ) = 2.57314098059343348567793e-08
    ( 3 | z | 11 ) = 2.43506666895108163200548e-10
    ( 4 | z | 0 ) = -0.00673826769913168314302121
    ( 4 | z | 1 ) = -0.0751877700374189439358474
    ( 4 | z | 2 ) = -0.490664749019337265156793
    ( 4 | z | 3 ) = -1.85111076485667558344517
    ( 4 | z | 4 ) = -2.9999999726693999946292
    ( 4 | z | 5 ) = -0.925555382428338013767188
    ( 4 | z | 6 ) = -0.0981329498038674558069161
    ( 4 | z | 7 ) = 0
    ( 4 | z | 8 ) = 0.000962609671304526085845732
    ( 4 | z | 9 ) = 8.63920057153276613757034e-05
    ( 4 | z | 10 ) = 3.11800332203032846587702e-06
    ( 4 | z | 11 ) = 5.14628196118686697135586e-08
    ( 5 | z | 0 ) = -0.000259176017145982943469529
    ( 5 | z | 1 ) = -0.00481304835652263032080844
    ( 5 | z | 2 ) = -0.0501251800249459603109337
    ( 5 | z | 3 ) = -0.294398849411602325787385
    ( 5 | z | 4 ) = -0.925555382428338013767188
    ( 5 | z | 5 ) = -0.999999990889800072224602
    ( 5 | z | 6 ) = 1.66533453693773481063545e-16
    ( 5 | z | 7 ) = 0.0981329498038674141735527
    ( 5 | z | 8 ) = 0.0250625900124729766860199
    ( 5 | z | 9 ) = 0.00288782901391357836595741
    ( 5 | z | 10 ) = 0.000172784011430655322751407
    ( 5 | z | 11 ) = 5.19667220338388105880601e-06
    ( 6 | z | 0 ) = -5.19667220338388105880601e-06
    ( 6 | z | 1 ) = -0.000172784011430655322751407
    ( 6 | z | 2 ) = -0.00288782901391357836595741
    ( 6 | z | 3 ) = -0.0250625900124729766860199
    ( 6 | z | 4 ) = -0.0981329498038674558069161
    ( 6 | z | 5 ) = 1.66533453693773481063545e-16
    ( 6 | z | 6 ) = 0.999999990889800183246905
    ( 6 | z | 7 ) = 0.925555382428338013767188
    ( 6 | z | 8 ) = 0.294398849411602325787385
    ( 6 | z | 9 ) = 0.0501251800249459603109337
    ( 6 | z | 10 ) = 0.00481304835652263032080844
    ( 6 | z | 11 ) = 0.000259176017145982943469529
    ( 7 | z | 0 ) = -5.14628196118686697135586e-08
    ( 7 | z | 1 ) = -3.11800332203032846587702e-06
    ( 7 | z | 2 ) = -8.63920057153276613757034e-05
    ( 7 | z | 3 ) = -0.000962609671304526085845732
    ( 7 | z | 4 ) = 0
    ( 7 | z | 5 ) = 0.0981329498038674141735527
    ( 7 | z | 6 ) = 0.925555382428338013767188
    ( 7 | z | 7 ) = 2.9999999726693999946292
    ( 7 | z | 8 ) = 1.85111076485667558344517
    ( 7 | z | 9 ) = 0.490664749019337209645641
    ( 7 | z | 10 ) = 0.0751877700374189439358474
    ( 7 | z | 11 ) = 0.00673826769913168314302121
    ( 8 | z | 0 ) = -2.43506666895108163200548e-10
    ( 8 | z | 1 ) = -2.57314098059343348567793e-08
    ( 8 | z | 2 ) = -1.03933444067677608470626e-06
    ( 8 | z | 3 ) = 5.29395592033937711917702e-22
    ( 8 | z | 4 ) = 0.000962609671304526085845732
    ( 8 | z | 5 ) = 0.0250625900124729766860199
    ( 8 | z | 6 ) = 0.294398849411602325787385
    ( 8 | z | 7 ) = 1.85111076485667558344517
    ( 8 | z | 8 ) = 4.99999995444900058316762
    ( 8 | z | 9 ) = 2.77666614728501315312315
    ( 8 | z | 10 ) = 0.686930648627072093503898
    ( 8 | z | 11 ) = 0.10025036004989190674408
    ( 9 | z | 0 ) = -5.21309471544019031202246e-13
    ( 9 | z | 1 ) = -8.1168888965036071633112e-11
    ( 9 | z | 2 ) = -1.61558713389263217748322e-27
    ( 9 | z | 3 ) = 1.03933444067677608470626e-06
    ( 9 | z | 4 ) = 8.63920057153276613757034e-05
    ( 9 | z | 5 ) = 0.00288782901391357836595741
    ( 9 | z | 6 ) = 0.0501251800249459603109337
    ( 9 | z | 7 ) = 0.490664749019337209645641
    ( 9 | z | 8 ) = 2.77666614728501315312315
    ( 9 | z | 9 ) = 6.99999993622859939534919
    ( 9 | z | 10 ) = 3.70222152971335116689033
    ( 9 | z | 11 ) = 0.883196548234806977362155
    ( 10 | z | 0 ) = -4.2600304552972045679068e-16
    ( 10 | z | 1 ) = -2.40741243048404481631997e-35
    ( 10 | z | 2 ) = 8.1168888965036071633112e-11
    ( 10 | z | 3 ) = 2.57314098059343348567793e-08
    ( 10 | z | 4 ) = 3.11800332203032846587702e-06
    ( 10 | z | 5 ) = 0.000172784011430655322751407
    ( 10 | z | 6 ) = 0.00481304835652263032080844
    ( 10 | z | 7 ) = 0.0751877700374189439358474
    ( 10 | z | 8 ) = 0.686930648627072093503898
    ( 10 | z | 9 ) = 3.70222152971335116689033
    ( 10 | z | 10 ) = 8.99999991800819998388761
    ( 10 | z | 11 ) = 4.62777691214168918065752
    ( 11 | z | 0 ) = 2.24207754291970731347797e-44
    ( 11 | z | 1 ) = 4.2600304552972045679068e-16
    ( 11 | z | 2 ) = 5.21309471544019031202246e-13
    ( 11 | z | 3 ) = 2.43506666895108163200548e-10
    ( 11 | z | 4 ) = 5.14628196118686697135586e-08
    ( 11 | z | 5 ) = 5.19667220338388105880601e-06
    ( 11 | z | 6 ) = 0.000259176017145982943469529
    ( 11 | z | 7 ) = 0.00673826769913168314302121
    ( 11 | z | 8 ) = 0.10025036004989190674408
    ( 11 | z | 9 ) = 0.883196548234806977362155
    ( 11 | z | 10 ) = 4.62777691214168918065752
    ( 11 | z | 11 ) = 10.9999998997877987960692
    ( 0 | zz | 0 ) = 121.649523127889011675506
    ( 0 | zz | 1 ) = 46.7450562876230861775184
    ( 0 | zz | 2 ) = 8.11725485031002591540528
    ( 0 | zz | 3 ) = 0.827488619744636944020044
    ( 0 | zz | 4 ) = 0.0489238718814696965653255
    ( 0 | zz | 5 ) = 0.0016234962634028499758182
    ( 0 | zz | 6 ) = 2.75412388858752698185105e-05
    ( 0 | zz | 7 ) = 2.24926027105023354282833e-07
    ( 0 | zz | 8 ) = 8.50707142661713386724502e-10
    ( 0 | zz | 9 ) = 1.42853489023546726912321e-12
    ( 0 | zz | 10 ) = 1.0567248174665075907848e-15
    ( 0 | zz | 11 ) = 5.24629952257418176836086e-19
    ( 1 | zz | 0 ) = 46.7450562876230861775184
    ( 1 | zz | 1 ) = 81.6495234922970212210203
    ( 1 | zz | 2 ) = 30.0850594039130143642069
    ( 1 | zz | 3 ) = 4.97700045658626777367317
    ( 1 | zz | 4 ) = 0.47661235957001524266019
    ( 1 | zz | 5 ) = 0.0258212397701610626987723
    ( 1 | zz | 6 ) = 0.000759576206249573497586436
    ( 1 | zz | 7 ) = 1.09118878350468524632104e-05
    ( 1 | zz | 8 ) = 7.05375682694173319072669e-08
    ( 1 | zz | 9 ) = 2.01356030941424942906576e-10
    ( 1 | zz | 10 ) = 3.8591594714742920671872e-13
    ( 1 | zz | 11 ) = 1.0567248174665075907848e-15
    ( 2 | zz | 0 ) = 8.11725485031002591540528
    ( 2 | zz | 1 ) = 30.0850594039130143642069
    ( 2 | zz | 2 ) = 49.649523783823418909833
    ( 2 | zz | 3 ) = 17.1272840499162910532505
    ( 2 | zz | 4 ) = 2.62180966129344916737409
    ( 2 | zz | 5 ) = 0.225986459445285475799992
    ( 2 | zz | 6 ) = 0.010419485029288647059964
    ( 2 | zz | 7 ) = 0.00024122417195760755643727
    ( 2 | zz | 8 ) = 2.59721230963264463259326e-06
    ( 2 | zz | 9 ) = 1.90747486575486655024307e-08
    ( 2 | zz | 10 ) = 2.01356030941424942906576e-10
    ( 2 | zz | 11 ) = 1.42853489023546726912321e-12
    ( 3 | zz | 0 ) = 0.827488619744636944020044
    ( 3 | zz | 1 ) = 4.97700045658626777367317
    ( 3 | zz | 2 ) = 17.1272840499162910532505
    ( 3 | zz | 3 ) = 25.6495240024682154000857
    ( 3 | zz | 4 ) = 7.87173022563291091557858
    ( 3 | zz | 5 ) = 1.05168246443156965241883
    ( 3 | zz | 6 ) = 0.0756109193704475879282967
    ( 3 | zz | 7 ) = 0.0027186076588524366384747
    ( 3 | zz | 8 ) = 6.84401605269522336858629e-05
    ( 3 | zz | 9 ) = 2.59721230963264463259326e-06
    ( 3 | zz | 10 ) = 7.05375682694173319072669e-08
    ( 3 | zz | 11 ) = 8.50707142661713386724502e-10
    ( 4 | zz | 0 ) = 0.0489238718814696965653255
    ( 4 | zz | 1 ) = 0.47661235957001524266019
    ( 4 | zz | 2 ) = 2.62180966129344916737409
    ( 4 | zz | 3 ) = 7.87173022563291091557858
    ( 4 | zz | 4 ) = 9.64952414823141424449204
    ( 4 | zz | 5 ) = 2.31839793106288638568913
    ( 4 | zz | 6 ) = 0.266618866000630116985803
    ( 4 | zz | 7 ) = 0.02548573934550163108681
    ( 4 | zz | 8 ) = 0.0027186076588524366384747
    ( 4 | zz | 9 ) = 0.000241224171957607529332215
    ( 4 | zz | 10 ) = 1.09118878350468524632104e-05
    ( 4 | zz | 11 ) = 2.24926027105023354282833e-07
    ( 5 | zz | 0 ) = 0.0016234962634028499758182
    ( 5 | zz | 1 ) = 0.0258212397701610626987723
    ( 5 | zz | 2 ) = 0.225986459445285475799992
    ( 5 | zz | 3 ) = 1.05168246443156965241883
    ( 5 | zz | 4 ) = 2.31839793106288638568913
    ( 5 | zz | 5 ) = 1.64952422111301411078443
    ( 5 | zz | 6 ) = 0.467287166206210524688203
    ( 5 | zz | 7 ) = 0.266618866000630116985803
    ( 5 | zz | 8 ) = 0.0756109193704475879282967
    ( 5 | zz | 9 ) = 0.010419485029288647059964
    ( 5 | zz | 10 ) = 0.000759576206249573497586436
    ( 5 | zz | 11 ) = 2.75412388858752698185105e-05
    ( 6 | zz | 0 ) = 2.75412388858752698185105e-05
    ( 6 | zz | 1 ) = 0.000759576206249573497586436
    ( 6 | zz | 2 ) = 0.010419485029288647059964
    ( 6 | zz | 3 ) = 0.0756109193704475879282967
    ( 6 | zz | 4 ) = 0.266618866000630116985803
    ( 6 | zz | 5 ) = 0.467287166206210524688203
    ( 6 | zz | 6 ) = 1.64952422111301411078443
    ( 6 | zz | 7 ) = 2.31839793106288638568913
    ( 6 | zz | 8 ) = 1.05168246443156965241883
    ( 6 | zz | 9 ) = 0.225986459445285475799992
    ( 6 | zz | 10 ) = 0.0258212397701610626987723
    ( 6 | zz | 11 ) = 0.0016234962634028499758182
    ( 7 | zz | 0 ) = 2.24926027105023354282833e-07
    ( 7 | zz | 1 ) = 1.09118878350468524632104e-05
    ( 7 | zz | 2 ) = 0.00024122417195760755643727
    ( 7 | zz | 3 ) = 0.0027186076588524366384747
    ( 7 | zz | 4 ) = 0.02548573934550163108681
    ( 7 | zz | 5 ) = 0.266618866000630116985803
    ( 7 | zz | 6 ) = 2.31839793106288638568913
    ( 7 | zz | 7 ) = 9.64952414823141424449204
    ( 7 | zz | 8 ) = 7.87173022563291358011384
    ( 7 | zz | 9 ) = 2.62180966129344827919567
    ( 7 | zz | 10 ) = 0.47661235957001524266019
    ( 7 | zz | 11 ) = 0.0489238718814696965653255
    ( 8 | zz | 0 ) = 8.50707142661713386724502e-10
    ( 8 | zz | 1 ) = 7.05375682694173319072669e-08
    ( 8 | zz | 2 ) = 2.59721230963264463259326e-06
    ( 8 | zz | 3 ) = 6.84401605269522336858629e-05
    ( 8 | zz | 4 ) = 0.0027186076588524366384747
    ( 8 | zz | 5 ) = 0.0756109193704475879282967
    ( 8 | zz | 6 ) = 1.05168246443156965241883
    ( 8 | zz | 7 ) = 7.87173022563291358011384
    ( 8 | zz | 8 ) = 25.6495240024682154000857
    ( 8 | zz | 9 ) = 17.1272840499162910532505
    ( 8 | zz | 10 ) = 4.97700045658626688549475
    ( 8 | zz | 11 ) = 0.827488619744636832997742
    ( 9 | zz | 0 ) = 1.42853489023546726912321e-12
    ( 9 | zz | 1 ) = 2.01356030941424942906576e-10
    ( 9 | zz | 2 ) = 1.90747486575486655024307e-08
    ( 9 | zz | 3 ) = 2.59721230963264463259326e-06
    ( 9 | zz | 4 ) = 0.000241224171957607529332215
    ( 9 | zz | 5 ) = 0.010419485029288647059964
    ( 9 | zz | 6 ) = 0.225986459445285475799992
    ( 9 | zz | 7 ) = 2.62180966129344827919567
    ( 9 | zz | 8 ) = 17.1272840499162910532505
    ( 9 | zz | 9 ) = 49.649523783823418909833
    ( 9 | zz | 10 ) = 30.0850594039130143642069
    ( 9 | zz | 11 ) = 8.11725485031002591540528
    ( 10 | zz | 0 ) = 1.0567248174665075907848e-15
    ( 10 | zz | 1 ) = 3.8591594714742920671872e-13
    ( 10 | zz | 2 ) = 2.01356030941424942906576e-10
    ( 10 | zz | 3 ) = 7.05375682694173319072669e-08
    ( 10 | zz | 4 ) = 1.09118878350468524632104e-05
    ( 10 | zz | 5 ) = 0.000759576206249573497586436
    ( 10 | zz | 6 ) = 0.0258212397701610626987723
    ( 10 | zz | 7 ) = 0.47661235957001524266019
    ( 10 | zz | 8 ) = 4.97700045658626688549475
    ( 10 | zz | 9 ) = 30.0850594039130143642069
    ( 10 | zz | 10 ) = 81.6495234922970212210203
    ( 10 | zz | 11 ) = 46.7450562876231003883731
    ( 11 | zz | 0 ) = 5.24629952257418176836086e-19
    ( 11 | zz | 1 ) = 1.0567248174665075907848e-15
    ( 11 | zz | 2 ) = 1.42853489023546726912321e-12
    ( 11 | zz | 3 ) = 8.50707142661713386724502e-10
    ( 11 | zz | 4 ) = 2.24926027105023354282833e-07
    ( 11 | zz | 5 ) = 2.75412388858752698185105e-05
    ( 11 | zz | 6 ) = 0.0016234962634028499758182
    ( 11 | zz | 7 ) = 0.0489238718814696965653255
    ( 11 | zz | 8 ) = 0.827488619744636832997742
    ( 11 | zz | 9 ) = 8.11725485031002591540528
    ( 11 | zz | 10 ) = 46.7450562876231003883731
    ( 11 | zz | 11 ) = 121.649523127888983253797

Best,
Sebastian

**Comment by sunqm** [comment]
This problem is fixed in libcint 2.5.4.
