### ISSUE TITLE
CCSD(T) not working for atoms with spin

### ISSUE THREAD

**Issue by gmwang18** [sunqm/pyscf#113]
ccsd_t not working for atoms with spin not zero.

Its working for molecules or atoms with spin = 0.

Here is my code:
```
from pyscf import gto, scf, cc
from pyscf.cc import ccsd_t

mol = gto.M(atom='C 0 0 0', basis='ccpvdz', spin=2)
mf = scf.RHF(mol).run()
mycc = cc.CCSD(mf)
mycc.kernel()

print(ccsd_t.kernel(mycc, mycc.ao2mo()))
```

**Comment by sunqm** [comment]
You'll need uccsd_t module for open shell system.  I didn't implement a general wrapper for ccsd(t).  You have to explicitly import uccssd_t::

from pyscf import gto, scf, cc
from pyscf.cc import uccsd_t

mol = gto.M(atom='C 0 0 0', basis='ccpvdz', spin=2)
mf = scf.RHF(mol).run()
mycc = cc.UCCSD(mf)
mycc.kernel()

print(uccsd_t.kernel(mycc, mycc.ao2mo()))

**Comment by gmwang18** [comment]
Thanks.

**Comment by gkc1000** [comment]
What does not work mean? Do you mean it gives a result that is incorrect? What is the error that you are seeing?

**Comment by gmwang18** [comment]
Sorry for the confusion. 
Here is the error:
converged SCF energy = -37.6933078196967  <S^2> = 2.0101294  2S+1 = 3.0067453
E(UCCSD) = -37.80947256838203  E_corr = -0.1161647486853136
Traceback (most recent call last):
  File "uccsdt.py", line 16, in <module>
    print(uccsd_t.kernel(mycc, mycc.ao2mo()))
  File "/home/apps/src/pyscf/pyscf/cc/uccsd_t.py", line 40, in kernel
    eris_vooo = numpy.asarray(eris.ovoo.transpose(1,2,0,3), order='C')
AttributeError: 'Dataset' object has no attribute 'transpose'

**Comment by gkc1000** [comment]
This looks like it is to do with HDF5, when things are stored on disk.

**Comment by tberkel** [comment]
Indeed: when the basis becomes large enough that ERIs are stored on disk,
the HDF5 datatype doesn't have .transpose(), so we typically cast to a np
array first.  Should be a quick fix.

-- 
Timothy C. Berkelbach
Neubauer Family Assistant Professor
Department of Chemistry and James Franck Institute
The University of Chicago

929 E. 57th Street, GCIS E133, Chicago, IL 60637
Cell: 917-446-2687
Office: 773-834-9879
E-mail: berkelbach@uchicago.edu
Web: berkelbachgroup.uchicago.edu
