### ISSUE TITLE
pyscf read molpro orbitals

### ISSUE THREAD

**Issue by lqhenwunai** [sunqm/pyscf#12]
Dear all, 

I want to use pyscf to read molecular orbitals from molpro.  My pyscf input for a La atom is:

import os
import numpy as np
from pyscf import gto, scf,symm,cc,tools
from pyscf.cc import ccsd_t
from pyscf.gto.basis import parse_molpro
from pyscf.x2c import x2c

mol=gto.Mole()
#unit in angstrom
mol.atom='''La 0 0 0
         '''
mol.symmetry='d2h'

dirnow = os.path.realpath(os.path.join(__file__, '..'))
basis_file_from_user = os.path.join(dirnow, 'cc-pvtz-x2c.dat')
mol.basis={'La':basis_file_from_user}

#-------------------------------------
#The following part is copied from examples/gto/30-read_molpro_orb.py

dat = open('orb.matrop').read().split('\n')
dat = ''.join(dat[2:-2])  # [2:-2] to skip comments
dat = np.array([float(x) for x in dat.split(',')[:-1]])  # [:-1] to remove last comma

#all orbitals in molpro symmetry order
#The dims is modified accordingly
dims = [22,16,16,11,16,11,11,6]  # orbitals in each irrep

off = 0
molpro_mo = []
for i, nd in enumerate(dims):
    molpro_mo.append(dat[off:off+nd**2].reshape(nd,nd))
    off += nd**2
mo = []
for i, ir in enumerate(mol.irrep_id):
    molpro_id = symm.param.IRREP_ID_MOLPRO['D2h'][ir]-1
    mo.append(np.dot(mol.symm_orb, molpro_mo[molpro_id]))
mo = np.hstack(mo)

#print np.einsum('ji,jk,ki->i', mo, mol.intor('cint1e_ovlp_sph'), mo)
#end of copy
#------------------------------------------------------------------------------------

mol.max_memory=8000
mol.charge=0
mol.spin=1  #molpro convention
mol.output='Lavtz.out'
mol.build()
hf=scf.RHF(mol).x2c()
hf.kernel()

However, when I run the script, it returns with:
    for i, ir in enumerate(mol.irrep_id):
TypeError: 'NoneType' object is not iterable

I tried to reproduce the result of the original example input, it returns with a different error message, but at least it enters in the regarding loop.
    mo.append(np.dot(mol.symm_orb, molpro_mo[molpro_id]))
ValueError: shapes (10,3) and (7,7) not aligned: 3 (dim 1) != 7 (dim 0)

I don't know what is wrong with my La input.

Many thanks for your help.

**Comment by sunqm** [comment]
same to issue https://github.com/pyscf/pyscf/issues/448
