### ISSUE TITLE
Better orbital projection

### ISSUE THREAD

**Issue by susilehtola** [sunqm/pyscf#128]
It appears that the way orbital projections currently work in pyscf is through the overlap
```
def project_mo_nr2nr(mol1, mo1, mol2):
    r''' Project orbital coefficients

    .. math::

        |\psi1> = |AO1> C1

        |\psi2> = P |\psi1> = |AO2>S^{-1}<AO2| AO1> C1 = |AO2> C2

        C2 = S^{-1}<AO2|AO1> C1
    '''
    s22 = mol2.intor_symmetric('int1e_ovlp')
    s21 = mole.intor_cross('int1e_ovlp', mol2, mol1)
    return lib.cho_solve(s22, numpy.dot(s21, mo1))
```

This is a very bad way to do it in e.g. geometry optimizations or potential energy surface scans, because the core orbitals will be messed up.

A better way would be e.g. to do the transport adiabatically, i.e. first translate the basis set in the checkpoint file to the current geometry, then project, and finally reorthonormalize...

**Comment by sunqm** [comment]
This projection scheme corresponds to the minimization of
\sum|<psi1 - psi2 | psi1- psi2>|^2
for all orbitals without any special treatment on the metric. When you input all orbitals for this projection, it's not surprising that core orbitals are dramatically changed. It does not favor any orbitals.

In the calculation like SCF or PES scanning, splitting the MO space into core, valence and unoccupied subspace and calling this function separately for these orbitals would give better projected core and valence space.  It can be an advanced projection scheme for SCF initial guess, but should not be the standard projection scheme.  I'll not change this function, but may implement the advanced projection in SCF initial guess.

**Comment by sunqm** [comment]
I will close this issue because the orbital projection (or initial guess) in the PES scanning and geometry optimization are actually done in the suggested adiabatic way, e.g. https://github.com/sunqm/pyscf/blob/master/pyscf/scf/hf.py#L1008
