### ISSUE TITLE
PyPI installation

### ISSUE THREAD

**Issue by babbush** [sunqm/pyscf#132]
I think it would be well worth the time to stage pyscf as a package on PyPI. This would allow PySCF to be installed effortlessly with "pip install pyscf". It would help less experienced users with the installation and also has other advantages. For instance, we have a package [OpenFermion](https://github.com/quantumlib/OpenFermion) which relies on PySCF as a plugin, through a plugin repo [OpenFermion-PySCF](https://github.com/quantumlib/OpenFermion-PySCF). If PySCF was listed on PyPI, then we could list PySCF as a requirement it would automatically install with our plugin. Also, this would enable us to easily setup continuous integration testing, e.g. using Travis, which is easier when packages are on PyPI.

**Comment by sunqm** [comment]
pip install is supported.  See http://sunqm.github.io/pyscf/install.html#installation-with-pip

**Comment by babbush** [comment]
I see that the project is registered with PyPI. However, unfortunately, I have tried installation using PyPI on three different mac computers and all three fail out of the box. Have you tried installing this way and had success on mac? Do you support only linux?

**Comment by gkc1000** [comment]
Currently development and testing is all Linux based. This is a good reminder we need to get a Mac!

Can you give the error message?

**Comment by babbush** [comment]
Mac 1:
Ryans-MacBook-Pro:~ ryanbabbush$ python -m pip install pyscf
Collecting pyscf
  Downloading pyscf-1.4.0.2.tar.gz (4.8MB)
    100% |████████████████████████████████| 4.8MB 141kB/s 
    Complete output from command python setup.py egg_info:
    /private/var/folders/1f/xjfzdtgj5rv4b91q96dld5gc0000gn/T/pip-build-MT1uxD/pyscf/pyscf/lib
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/1f/xjfzdtgj5rv4b91q96dld5gc0000gn/T/pip-build-MT1uxD/pyscf/setup.py", line 173, in <module>
        version='3.0')
      File "/private/var/folders/1f/xjfzdtgj5rv4b91q96dld5gc0000gn/T/pip-build-MT1uxD/pyscf/setup.py", line 135, in search_lib_path
        paths = os.environ["LD_LIBRARY_PATH"].split(os.pathsep)
      File "/Users/ryanbabbush/anaconda/lib/python2.7/UserDict.py", line 40, in __getitem__
        raise KeyError(key)
    KeyError: 'LD_LIBRARY_PATH'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/1f/xjfzdtgj5rv4b91q96dld5gc0000gn/T/pip-build-MT1uxD/pyscf/

**Comment by babbush** [comment]
Mac2:
babbush-macbookair:Desktop babbush$ python -m pip install pyscf
Collecting pyscf
  Using cached pyscf-1.4.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/vj/95l4k5tn2gv9jwpdcy1429pm0079c3/T/pip-build-334yP4/pyscf/setup.py", line 66, in <module>
        blas_lib_dir = np_blas['library_dirs']
    KeyError: 'library_dirs'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/vj/95l4k5tn2gv9jwpdcy1429pm0079c3/T/pip-build-334yP4/pyscf/
babbush-macbookair:Desktop babbush$

**Comment by babbush** [comment]
I am traveling now but I recall a third error message on my girlfriend's mac when I tried a few days ago! I will paste that when I'm back home.

**Comment by sunqm** [comment]
The error on Mac 1 is due to the platform dependent variable LD_LIBRARY_PATH.  It is easy to fix.

The second error is really difficult to solve.  Pypi does not have a mechanism to search external libraries such as blas.  I did a trick to extract the blas information from numpy.  It was working fine in my test environment where the numpy library was manually compiled.  But the precompiled numpy library on pypi uses a trick to hide the real blas library that it links against.

**Comment by sunqm** [comment]
If all dependent libraies (numpy, scipy, h5py) are installed from pypi, "pip install pyscf" on Mac is supported.  However, the default pip install does not include dft module.
