### ISSUE TITLE
subprocess.check_call() function hangs in dmrgscf module

### ISSUE THREAD

**Issue by hungpham2017** [sunqm/pyscf#133]
Hello,

I got a problem when testing dmrgscf module in PySCF 1.4 using python 3.6.2.
(the standalone block-1.5.3 code works well).

After running a scf() calculation, the subprocess.check_call() function will hang if it is called in dmrgscf.executeBLOCK().
I did a simple test with check_call function by running an pyscf.scf and call subprocess.check_call('ls')
It turned out that calling the scf.kernel() makes .check_call() hang.
Do you have any ideal why this happens?

Thank you very much for your help.

**Comment by sunqm** [comment]
I'm not quite clear how to reproduce the problem as you described.  Do you have a small test script for this problem?

**Comment by hungpham2017** [comment]
Please see the attached for the test.
the first: check_call('ls', shell = True) is working
the second (after calling m.scf()) will hang

Thank you,

**Comment by sunqm** [comment]
I didn't find attached file.

I tried python 3.5.2 the following code

```
$ cat h2.py
from pyscf import gto, scf
mol = gto.M(atom='H 0 0 0; H 0 0 1')
mf = scf.RHF(mol)
mf.kernel()

$ cat call.py
import subprocess
subprocess.check_call('python3 tmp.py', shell=True)
```
I executed the code
```
$ python3 call.py
```
This outputs normally
converged SCF energy = -1.06610864931794

Do these scripts get problem in your python 3.6 environment?

**Comment by hungpham2017** [comment]
Hi,

It is running okay if call.py and h2.py are  two separate files. 
But problem when I execute h2-call.py
```
$ cat h2-call.py 
from pyscf import gto, scf
mol = gto.M(atom='H 0 0 0; H 0 0 1')
mf = scf.RHF(mol)
mf.kernel()

import subprocess
subprocess.check_call('python3 h2.py', shell=True)
```

execute the code:

```$ python h2-call.py```

it will hang

thank you

**Comment by sunqm** [comment]
I cannot reproduce this problem with anaconda 5.0 running in python 3.6.

check_call with shell=True  initializes a non-interactive shell and read the configs of ~/.bashrc.  My guess is that your .bashrc may contain some settings that mess up the environment variables for anaconda.  You can try to remove the shell profile files first (~/.bashrc, ~/.profile, ~/.bash_profile) and run this script again.

shell=True is not a recommended way to use python subprocess module.  I noticed in pyscf dmrgscf module, we used several places shell=True when calling check_call.  I will remove it in the future.

**Comment by hungpham2017** [comment]
You're right.
There should be something messing up with my miniconda environment since there was no problem when I ran the same script not on the miniconda.
However,  it is still not working even if I tried to remove the .bashrc or simplify it, like this:

```
export LD_LIBRARY_PATH=$HOME/miniconda/envs/umn/lib:$LD_LIBRARY_PATH
export PATH=$HOME/miniconda/bin:$PATH
```

Install pyscf (python install pyscf) in conda environment does not help either.

Only the subprocess module has this problem (after running a scf calculation) , the os.system does not have this problem.

Do you have any idea what could be the reason?

**Comment by sunqm** [comment]
Does subprocess.check_call(['ls']) work (without shell=True)?
Does subprocess.check_output('ls -a', shell=True) work?
Does subprocess.call('ls -a', shell=True) work?

If you only import gto module and initialize mol object (without calling scf),  does it work?

Is it possible a mixing of Python 2 and Python 3 environment?  What is your $PYTHONPATH?
Mostly, these kinds of problems are due to python GIL.  Before calling subprocess.check_call, you can check the import lock (may not work for python 3.6)
```
import imp
print(imp.lock_held())
```
Pyscf basically uses python built in modules plus numpy, scipy and h5py.  I think numpy, scipy should be safe for any python runtime conditions.  I'm not 100% sure whether h5py is safe.  Assuming h5py has no problem, I don't think scf code could lead to side effects to any python modules.

**Comment by hungpham2017** [comment]
```
Does subprocess.check_call(['ls']) work (without shell=True)?
Does subprocess.check_output('ls -a', shell=True) work?
Does subprocess.call('ls -a', shell=True) work?
```
None of them works after calling mf.kernel()

`If you only import gto module and initialize mol object (without calling scf), does it work?`

The problem just happened after I call mf.kernel().

```
import imp
print(imp.lock_held())
```
This gives a 'False'

The problem just happened after I call mf.kernel().
it could be something wrong with my miniconda environment since it doesn't happen elsewhere as far I  tested.
I will try to figure it out and let you know if I find something.
Thank you very much for your help.

**Comment by sunqm** [comment]
mf.kernel() will output message to stdout.  I suspect the stdout buffer got problem in subprocess.  What about the following script?
```
from pyscf import gto
mol = gto.M(atom='H 0 0 0; H 0 0 1', verbose=4)
import subprocess
subprocess.check_call('ls -a', shell=True)
```

**Comment by hungpham2017** [comment]
The script you just sent worked fine. There was no problem if subprocess.check_call() were called couple times.

**Comment by hungpham2017** [comment]
Hello,

I want to follow up the frozen subprocess issue after calling mf.kernel().
I inspected the gto class as well and found that the problem may relate to some gto C library.
Specifically, libcgto.CINTc2s_ket_sph causes the frozen.

In the script below, the problem happens with a particular combination of **l** and **error** value.
For example, **l=9 and error = 48** make the subprocess hangs.
However, **l=9 and error = 47** DOES NOT
I think you have better idea what is going on in the libcgto.CINTc2s_ket_sph.
Thank you in advance for helping

Here is the script:
```
import ctypes
import numpy
from pyscf.gto import moleintor
import subprocess
import sys
import os
	

l = 9 	
error = 47	# if error >= 48 the subprocess will hang
	
cmat = numpy.eye(100)
c2sph = numpy.zeros((100,100), order='F')
fn = moleintor.libcgto.CINTc2s_ket_sph

fn(c2sph.ctypes.data_as(ctypes.c_void_p), ctypes.c_int(error),cmat.ctypes.data_as(ctypes.c_void_p), ctypes.c_int(l))

subprocess.check_call('ls', shell=False)
```

**Comment by sunqm** [comment]
It still works fine on our cluster.

Is it a clean compilation and installation?  If it was an update installation in an old pyscf repo, makefile maybe mess up the libcint library version.

**Comment by hungpham2017** [comment]
I completely removed/reinstalled the pyscf but it didn't help.
This problem is somehow system-dependent. In particular, I have observed that:
- Non miniconda environment, the subprocess works fine.
- In miniconda env, depending on the certain computer, the problem happens at the different conditions.
Computer 1: calling **cart2sph(l)** (in pyscf/mole.py) with **l = 9** makes the subprocess hangs
Computer 2:  the subprocess hangs only if **l >= 10**

This is weird and I am still looking at the difference between these CPUs to understand the reasons behind it.
Thank you so much for your help. I keep you posted if I find out the reason.

**Comment by hungpham2017** [comment]
I tried the same script with **anaconda** environment.
**There is NO such a problem at all**. So, I may just blame **miniconda**. 
I still don't know the real reason behind this though, but I think I just switch to using **anaconda** instead.
Thank very much for your helpful support.
I really appreciate your time spending for this 'weird' problem.
