### ISSUE TITLE
Building from source with OpenBLAS

### ISSUE THREAD

**Issue by Diazonium** [sunqm/pyscf#135]
I have tried to build from source, with no MKL, but OpenBLAS is installed. 

However, the cmake script does not seem to be able to find and use OpenBLAS, and prints this error message: 
`CMake Error at /usr/share/cmake-3.0/Modules/FindBLAS.cmake:678 (message):
  A required library with BLAS API not found.  Please specify library
  location.
`

**Comment by sunqm** [comment]
You can create a file in pyscf/lib/cmake.arch.inc, in which specifying the BLAS library paths, eg
```
set(BLAS_LIBRARIES "-L/path/to/openblas -lopenblas")
```

**Comment by Diazonium** [comment]
That did not work at all. 
However I have found out that CMake versions >= 3.6.0 can recognize OpenBLAS, while lower versions cannot. Installing a newer version of CMake in my home directory and then prepending the /bin directory of said new cmake to PATH, allowed me to use CMake 3.8.2, that found OpenBLAS without any issues.
I recommend updating the documentation to include this.

**Comment by gkc1000** [comment]
Hi, could you give some more info as to what did not work means? Cmake
should be setting BLAS_LIBRARIES. Do you have the linker error?

**Comment by Diazonium** [comment]
Even though I created the file with `set(BLAS_LIBRARIES "-L/path/to/openblas -lopenblas")`, I received the same error. I suspect this is due to older versions of CMake not recognizing OpenBLAS as a valid BLA_VENDOR, thus FindBLAS in cmake will always fail. But I am not a CMake expert by any means.

**Comment by sunqm** [comment]
You may need to update the code.  As discussed in issue #122 and #124, we don't require cmake to resolve everything automatically and therefore introduce the custom config file recently. This custom config file was added in dev branch a few weeks ago and supported in master branch just in the last commit f36d0b7.

**Comment by Diazonium** [comment]
I have downloaded the source for 1.4 stable, so most likely that was the issue.

On a different note, for anyone who wants to use OpenBLAS: for numpy to be able to load OpenBLAS, it must be compiled with DYNAMIC_ARCH enabled. Otherwise, some of the symbols numpy expects to be present in the BLAS library will be missing, and numpy will fail to load.

**Comment by sunqm** [comment]
For OpenBLAS error in numpy, is it an OSError that complains about "undefined symbol"?  I think DYNAMIC_ARCH is not supposed to solve this problem.  LD_PRELOAD is probably the solution for this kind of problem.
https://github.com/numpy/numpy/blob/master/INSTALL.rst.txt#ubuntudebian

**Comment by Diazonium** [comment]
I am not sure where I read that, I was just sifting through search results.
Also I used the numpy version supplied by the Debian 8 repos, probably a quite old version, but it did end up working.
