### ISSUE TITLE
Bug in dmrgscf/chemps2.py?

### ISSUE THREAD

**Issue by hungpham2017** [sunqm/pyscf#137]
Hello,

I did a test on CASSCF calculation using three different solvers for N2: DMRG CheMPS2, DMRG BLOCK, and FCI in pyscf.

> FCI in pyscf:              E1 = -108.59972854237726
> DMRG in BLOCK:      E2 = -108.59972853684695
> DMRG in CheMPS2: E3 = -4.90129384641262

As you may see, the CheMPS2 gives the wrong energy.
I looked at the chemps2.py module, I found that the Energy is just the CAS energy without the core contribution (ecore).
Actually, if the ecore is passed into the chemps2 kernel(), then we will get the correct energy.
Also, I noticed that in chemps2.py, the kernel() exports the Energy and 2-rdm instead of CI vector like FCI solver in pyscf.
I wonder if there is any reason why you did so, and how I can get the ci vector if the chemps2 solver is used.

Here is the test script:

```
from pyscf import gto
from pyscf import scf
from pyscf import mcscf
from pyscf import dmrgscf

b = 1.4
mol = gto.Mole()
mol.build(
verbose = 0,
output = None,
atom = [
    ['N',(  0.000000,  0.000000, -b/2)],
    ['N',(  0.000000,  0.000000,  b/2)], ],
basis = {'N': 'sto6g', },
)
m = scf.RHF(mol)
m.conv_tol = 1e-9
m.scf()

mc1 = mcscf.CASCI(m, 4, 4)
E1 = mc1.kernel()[0]

mc2 = mcscf.CASCI(m, 4, 4)
mc2.fcisolver = dmrgscf.DMRGCI(mol)
E2 = mc2.kernel()[0]

mc3 = mcscf.CASCI(m, 4, 4)
mc3.fcisolver = dmrgscf.CheMPS2(mol)
E3 = mc3.kernel()[0]
```

Thank you

**Comment by sunqm** [comment]
DMRG does not have CI vector.   Strictly speaking, the chemps2 kernel should return MPS, and the make_rdm* function should use the MPS to compute density matrix.  When I implemented the interface some years ago, I was not sure how to access MPS from chemps2 program and reuse them in make_rdm* functions properly. So the chemps2 kernel function returns also the density matrices which is then used in the make_rdm* functions.

**Comment by sunqm** [comment]
BTW, using the script you provided, I got -108.599800208383 with FCI solver.

**Comment by hungpham2017** [comment]
You're right, it was a typo for FCI solver. I put the HF energy instead.
Only the chemps2 got wrong result.
