### ISSUE TITLE
Dynamical polarizability from Casida's TDDFT

### ISSUE THREAD

**Issue by kovalp** [sunqm/pyscf#139]
The TDDFT class implements only excitation energies and Casida eigenvectors. It would be nice to provide an interface or an example how to build out of this data the expectation values. For instance, the dipole dynamical polarizability of oscillator strength.

**Comment by kovalp** [comment]
I think it would be of help for several people to incorporate into the existing tddft class a subroutine as following

def comp_polariz_ave(mf, gto, tddft, comega):
  gto.set_common_orig((0.0,0.0,0.0))
  ao_dip = gto.intor_symmetric('int1e_r', comp=3)
  occidx = np.where(mf.mo_occ==2)[0]
  viridx = np.where(mf.mo_occ==0)[0]
  mo_coeff = mf.mo_coeff
  mo_energy = mf.mo_energy
  orbv,orbo = mo_coeff[:,viridx], mo_coeff[:,occidx]
  vo_dip = np.einsum('cmb,bn->cmn', np.einsum('am,cab->cmb', orbv, ao_dip), orbo)
  vo_dip = vo_dip.reshape((3,int(vo_dip.size/3)))
  p = np.zeros((comega.size), dtype=np.complex128)
  for (x,y),e in zip(tddft.xy, tddft.e):
    dip = np.dot(vo_dip, np.sqrt(2.0)*(x+y)) # Normalization ?
    osc_strength = (2.0/3.0)*(dip*dip).sum()
    for iw,w in enumerate(comega):
      p[iw] += osc_strength*((1.0/(w-e))-(1.0/(w+e)))
  return p

**Comment by kovalp** [comment]
sorry, I don't know how to insert decently a multi-line code. In first version it swallows the stars * and in the second it swallows the end lines.

**Comment by sunqm** [comment]
This is available in pyscf-1.5.
https://github.com/sunqm/pyscf/blob/master/pyscf/tdscf/rhf.py#L773
