### ISSUE TITLE
Overlap matrix at two different k-point values

### ISSUE THREAD

**Issue by hungpham2017** [sunqm/pyscf#143]
Hello,

I am not really sure if there is any function in the pbc module that allows one to calculate the overlap matrix (or maybe one-e integral) at two different k-point values.
S(k1,k2) = < psi(k1)| psi(k2)> instead of  S(k) = < psi(k)| psi(k)>

Thank you,
Hung

**Comment by sunqm** [comment]
Assuming k1 and k2 are both in the first Brillouin zone, when k1 != k2,  S(k1,k2) should be zero.

When k1 == k2,  S(k1,k1) can be evaluated by cell.pbc_intor function:
s_k1 = cell.pbc_intor('int1e_ovlp', kpt=k1)

**Comment by hungpham2017** [comment]
`\langle \mu | intor | \nu \rangle, \mu \in cell1, \nu \in cell2`

**Comment by tberkel** [comment]
Perhaps you are asking about overlap integrals (or other one-electron
integrals) between the *cell-periodic* part of the (AO or MO) Bloch
functions?  These are the objects needed, for example, in the modern theory
of polarization or Berry's phase calculations.

I don't think we currently support this, but it would be an easy addition
to the code -- the cell-periodic part u_{nk}(r) is trivially related to the
AO/MO Bloch functions phi_{nk}(r) via
u_{nk}(r) = e^{-ikr} phi_{nk}(r) which is an operation we do all the time
on the real-space grid or could easily do with analytic GTO integrals.

-- 
Timothy C. Berkelbach
Neubauer Family Assistant Professor
Department of Chemistry and James Franck Institute
The University of Chicago

929 E. 57th Street, GCIS E133, Chicago, IL 60637
Cell: 917-446-2687
Office: 773-834-9879
E-mail: berkelbach@uchicago.edu
Web: berkelbachgroup.uchicago.edu

**Comment by hungpham2017** [comment]
Yes, that is exactly what I would like to compute by PySCF.
I am currently interfacing Wannier90 with PySCF to obtain the Wannier functions so the overlap matrix for the *cell-periodic* part of the MO Bloch (M_{m,n}^{k,b}) and the projection matrix  A_{m,n}^{k} are needed. I am actually preparing a short document containing all the basic equations for this wannierizing process so it will be easy to show what I need.
I would greatly appreciate any advice on how to get the periodic part from PySCF modules.

**Comment by gkc1000** [comment]
Hi Hung - what kind of Wannier functions are you looking for, or what do
you need them for? We have been looking into implementing some Wannier
things for the PBC code.

**Comment by hungpham2017** [comment]
Hello Qiming,
I have been interfacing Wannier90 ([www.wannier.org](url))  to PySCF to compute the **maximally-localised Wannier functions (MLMF)**. Wannier90 has been interfaced with VASP, QuantumExpresso, Siesta, etc.
I need this for the post-HF treatments and the embedding theories (e.g. DMET) for periodic systems based on the PBC code of PySCF.
I already made Wannier90 working as a python module (called pyWannier90).
So I am working on calculating the overlap matrix M_{m,n}^{k,b} and the projection matrix A_{m,n}^{k} (see Martin p418 or [https://journals.aps.org/prb/abstract/10.1103/PhysRevB.56.12847](url)) and passing them to pyWannier90 to obtain the MLWF.
I am not sure if this work is overlapping with what you have been doing on Wannier functions and will be released soon in the future version of PySCF.
  
Thank you

**Comment by sunqm** [comment]
The following pseudo code should be the overlap matrix of the cell-periodic part of Bloch function. Does it correspond to the overlap matrix you needed?
```
from pyscf.pbc.dft import gen_grid, numint
cell = ...
grids = gen_grid.UniformGrids(cell)
grids.build()
ao = numint.eval_ao(cell, grids.coords, kpt=k1)
u_k1 = np.einsum('x,xi->xi', np.exp(-1j*np.dot(grids.coords, k1)), ao)
ao = numint.eval_ao(cell, grids.coords, kpt=k2)
u_k2 = np.einsum('x,xi->xi', np.exp(-1j*np.dot(grids.coords, k2)), ao)
s_k1k2 = np.einsum('xi,xj->ij', u_k1.conj(), u_k2)
```

**Comment by hungpham2017** [comment]
I think this seems to be what I need but I need to test it myself though.
I was expecting an analytical for this overlap matrix but this is good enough for me now.

Another follow-up question on how to get AO numerically in real space of a cell object.
It is something like the numint.eval_ao() but in real space and at the reference cell. 
Is it possible to get it? 
I need to evaluate the overlap between AOs of **_a cell (cell 1) in k-space_** with the AO of another _**cell (cell2) in real space**_. It is the projection matrix A_mn^k that I mentioned ealier.
I think of the pyscf.pbc.gto.cell.intor_cross() but this is for two cells at some k-point.

Thank you so much for your help. I really appreciate this.

**Comment by sunqm** [comment]
I realized the overlap is actually an analytical FT of the product of two orbitals.  This example shows the overlap https://github.com/sunqm/pyscf/blob/dev/examples/pbc/30-overlap_periodic_cell.py#L22

**Comment by hungpham2017** [comment]
This is great, much simpler!!!
Thank you so much
btw, did you have time to look at the overlapping between **"AOs of a cell (cell 1) in k-space** with the **AO of another cell (cell2) in real space"** above/

**Comment by sunqm** [comment]
The overlap for "(pbc) AOs of a cell (cell 1) in k-space with the (non-pbc) AO in real space" is identical to the regular overlap matrix (per unit-cell) of two pbc-AO basis
```
s = cell.pbc_intor('int1e_ovlp', kpt=k1)
```
Assume AO in bra is periodic basis and the AO in ket is a GTO function in real space.  Because of translational symmetry of AO in bra, this overlap has
```
<AO(k,r) | AO(r)> = <AO(k,r-T) |AO(r-T)> = <AO(k,r) | exp(i k*T) AO(r-T)> = 1/N \sum_{T} <AO(k,r) | exp(i k*T) AO(r-T)> = 1/N <AO(k,r) | AO(k,r)>
```
