### ISSUE TITLE
Spin setting not passed from Mole object to FCI solver?

### ISSUE THREAD

**Issue by emstoudenmire** [sunqm/pyscf#146]
Hi, I am trying some simple single-atom FCI calculations and trying to change the total spin of the wavefunction. I managed to do this by using the fci.addons.fix_spin_ method applied to the FCI solver. However, that was only after I tried passing the total spin through a Mole object used to define the problem. Please see the sample code below. Isn't the spin set in the Mole object supposed to be recognized by the FCI object later? Instead I always get the same energy from this code whether tspin is set to 1 or to 3. Thanks -

    from pyscf import gto,scf,fci

    tspin = 1
    #tspin = 3

    mol = gto.Mole()
    mol.build(
        atom = "N 0 0 0;", spin = tspin,
        basis = "sto3g"
        )

    print("Using total spin S=%d/2"%tspin)

    myhf = scf.RHF(mol)
    myhf.kernel()

    cisolver = fci.FCI(mol, myhf.mo_coeff)
    print('E(FCI) = %.12f' % cisolver.kernel()[0])

**Comment by sunqm** [comment]
The spin setting is recognized in FCI object.  However, the two FCI calculations converge to the same ground state (quartet), with  Sz=1/2 for one solution and Sz=3/2 for the other.  Note, the FCI implementation does not guarantee S^2 value. The S^2 value can be checked with the following code
```
norb = myhf.mo_coeff.shape[1]
nelec = mol.nelec
s2 = cisolver.spin_square(cisolver.ci, norb, nelec)[0]
print s2

```
A workaround for the spin problem is to call the "fix_spin" function which applies a level shift to the CI determinants of wrong spin
```
cisolver = fci.FCI(mol, myhf.mo_coeff)
cisolver = fci.addons.fix_spin_(cisolver)
print('E(FCI) = %.12f' % cisolver.kernel()[0])
norb = myhf.mo_coeff.shape[1]
nelec = mol.nelec
s2 = cisolver.spin_square(cisolver.ci, norb, nelec)[0]
print s2
```

**Comment by emstoudenmire** [comment]
Thanks for the quick reply. I had thought the spin setting was fixing the S^2 value through the "S" variable. I appreciate the code to get around this issue.
