### ISSUE TITLE
init_guess_by_minao fails for large-core ECP with small basis

### ISSUE THREAD

**Issue by bogdanoff** [sunqm/pyscf#150]
I use large-core ECP with small  basis to represent some not very important atoms in calculation.
In the example below I get an error related to non-diagonal s12 with minao basis using master branch, but the calculation runs fine with 1.3.
If I add the d function, the calculation goes fine with 1.4 too.

Results using pyscf 1.3 suggest that as expected adding a d function here doesn't change anything:
without d function
>converged SCF energy = -29.7458248590998

with d function
>converged SCF energy = -29.7458248590998

If I don't use minao guess (using dm frim chk file) the calculation runs fine up to the mf.analyze(), where population analysis fails again because s12 with minao is computed.

Example that gives an error:
```
#!/usr/bin/env python
from pyscf import gto, scf
mol = gto.Mole()
mol.verbose = 5
mol.build(
atom='''
 La 0. 0. 0.''',
            basis={'La': gto.parse('''
             #BASIS SET: (4s4p3d) -> [2s2p1d] Basis  for PP46MWB
La   S
      5.087399            -0.417243
      4.270978             0.886010
      1.915458            -1.419752
La   S
      0.525596             1.000000
La   P
      3.025161             0.538196
      2.382095            -0.981640
      0.584426             1.239590
La   P
      0.260360             1.000000
# La   D
#       1.576824            -0.096944
#       0.592390             0.407466
#       0.249500             0.704363
''')},
            ecp = {'La': gto.basis.parse_ecp('''
La nelec 46
La ul
2      1.000000000            0.0000000      
La S
2      3.30990000            91.9321770
2      1.65500000            -3.7887640
La P
2      2.83680000            63.7594860
2      1.41840000            -0.6479580
La D
2      2.02130000            36.1191730
2      1.01070000             0.2191140
La F
2      4.02860000           -36.0100160
            ''')},
    charge=3,
)

mf = scf.RHF(mol)
mf.kernel()
mf.analyze()
```

Error with the master branch:
```
  File "ecp.py", line 160, in <module>
    mf.kernel()
  File "/u/nikb/src/pyscf-master/pyscf/scf/hf.py", line 1308, in kernel
    return self.scf(dm0)
  File "~/src/pyscf-master/pyscf/scf/hf.py", line 1302, in scf
    conv_check=self.conv_check)
  File "~/src/pyscf-master/pyscf/scf/hf.py", line 96, in kernel
    dm = mf.get_init_guess(mol, mf.init_guess)
  File "~/src/pyscf-master/pyscf/scf/hf.py", line 1252, in get_init_guess
    dm = self.init_guess_by_minao(mol)
  File "~/src/pyscf-master/pyscf/scf/hf.py", line 1204, in init_guess_by_minao
    return init_guess_by_minao(mol)
  File "~/src/pyscf-master/pyscf/scf/hf.py", line 338, in init_guess_by_minao
    occ_add, basis_add = minao_basis(symb, nelec_ecp)
  File "~/src/pyscf-master/pyscf/scf/hf.py", line 321, in minao_basis
    if abs(numpy.linalg.det(s12)) > .1:
  File "/afs/ipp/.cs/anaconda/amd64_generic/2/5.0.0/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 1801, in det
    _assertNdSquareness(a)
  File "/afs/ipp/.cs/anaconda/amd64_generic/2/5.0.0/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 212, in _assertNdSquareness
    raise LinAlgError('Last 2 dimensions of the array must be square')
numpy.linalg.linalg.LinAlgError: Last 2 dimensions of the array must be square
```

**Comment by sunqm** [comment]
The update solves the crash. Note the population analysis of mf.analyze() may have problems when this kind of ecp basis is used.  In the normal cases, the analyze function tries to identify the valence orbitals and localize them for Mulliken population.  In this system, the program cannot identify the valence space.

**Comment by bogdanoff** [comment]
Thanks, it works like a charm!
I can now conveniently use mf.analyze(with_meta_lowdin=False) to get Mulliken populations.

I have a related question, is there a way to have ECP without basis functions at all, i.e. total-ion-potentials (TIPs). This is extremely useful in QM/MM framework when there are many neighbors to be included.

**Comment by bogdanoff** [comment]
I found another use of meta-Lowdin analysis in MCSCF module. If natural orbitals are requested,  the meta-Lowdin analysis will be automatically done with the  logger.INFO level.

**Comment by sunqm** [comment]
qmmm interface is available  https://github.com/sunqm/pyscf/blob/master/pyscf/qmmm/itrf.py#L44
This interface supports to input a set of charges, which are treated as point nucleus.  It does not support ECP-like potentials.

**Comment by sunqm** [comment]
mc.analyze function outputs the population analysis and other information if verbose level is high enough (>= logger.INFO).  If you want to access the natural orbitals, it's recommended to call the mc.canonicalize(natorb=True) method.
