### ISSUE TITLE
Rename tddft module to tdscf

### ISSUE THREAD

**Issue by tberkel** [sunqm/pyscf#151]
As the title says, I tentatively propose that we rename the `tddft` module to `tdscf`, since it implements both HF and KS DFT (I don't think finding CIS inside the `tddft` modules is very intuitive).  However, either solution is "asymmetric" in the sense that the parent pyscf directory contains separate `scf` and `dft` modules, where `scf` exclusively means HF.  Alternatively, we could put the excited-state files into their respective `scf`/`dft` directories, but that might be a confusing place to look.  I'm not sure what the best solution is.

**Comment by sunqm** [comment]
As of 1.5 release, tddft is an alias of tdscf.
