### ISSUE TITLE
error: identifier "XC_FAMILY_HYB_GGA" is undefined

### ISSUE THREAD

**Issue by chchang6** [sunqm/pyscf#16]
I'm trying to build PySCF on CentOS 7.7 with this rough background:
```(/home/cchang/.conda-envs/builds) [cchang@el3 build]$ ml list

Currently Loaded Modules:
  1) cmake/3.12.3   2) gcc/8.4.0   3) comp-intel/2020.1.217   4) mkl/2020.1.217   5) hdf5/1.10.6/intel-serial   6) conda/mini_py37_4.8.3
```

The automated build fails, so I've built xcfun, libxc, and libcint according to the pyscf docs. Relevant configuration commands were

xcfun: commit 8ec13b06e06feccbc9e968665977df14d7bfdff8
`CC=icc CXX=icpc cmake -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_SHARED_LIBS=1 -DXCFUN_MAX_ORDER=3 -DCMAKE_INSTALL_PREFIX=/projects/qca4cesr/cchang -DCMAKE_INSTALL_LIBDIR=lib64 ..`

libxc: commit 6f9545ff98a4a25ca5b1ee8e127858304a8d636e
`./configure --prefix=/projects/qca4cesr/cchang --libdir=/projects/qca4cesr/cchang/lib64 --enable-shared --disable-static --enable-vxc --enable-fxc --enable-kxc --disable-fortran CC=icc FC=ifort`

libcint: commit b8594f1d27c3dad9034984a2a5befb9d607d4932
`CC=icc cmake -DWITH_F12=1 -DWITH_RANGE_COULOMB=1 -DWITH_COULOMB_ERF=1 -DCMAKE_INSTALL_PREFIX:PATH=/projects/qca4cesr/cchang -DCMAKE_INSTALL_LIBDIR:PATH=/projects/qca4cesr/cchang/lib64 ..`

For PySCF (commit 53e2069b4a3a2e0616bdf4d8c2e3f898c10a8330), it was
`CC=icc CXX=icpc cmake -DBUILD_LIBCINT=0 -DBUILD_LIBXC=0 -DBUILD_XCFUN=0 -DCMAKE_INSTALL_PREFIX=/projects/qca4cesr/cchang ..`

The "make" step after the last configuration fails with (just including the characteristic error message types for brevity)

```(/home/cchang/.conda-envs/builds) [cchang@el3 build]$ pwd
/projects/qca4cesr/cchang/QC-DMET/pyscf/pyscf/lib/build
(/home/cchang/.conda-envs/builds) [cchang@el3 build]$ make
...
[ 98%] Building C object dft/CMakeFiles/xc_itrf.dir/libxc_itrf.c.o
/projects/qca4cesr/cchang/QC-DMET/pyscf/pyscf/lib/dft/libxc_itrf.c(133): error: identifier "XC_FAMILY_HYB_GGA" is undefined
          case XC_FAMILY_HYB_GGA:
               ^
...
/projects/qca4cesr/cchang/QC-DMET/pyscf/pyscf/lib/dft/libxc_itrf.c(687): error: struct "xc_func_type" has no field "cam_omega"
                          if (func.cam_omega != 0) {
...
compilation aborted for /projects/qca4cesr/cchang/QC-DMET/pyscf/pyscf/lib/dft/libxc_itrf.c (code 2)
make[2]: *** [dft/CMakeFiles/xc_itrf.dir/build.make:82: dft/CMakeFiles/xc_itrf.dir/libxc_itrf.c.o] Error 2
make[1]: *** [CMakeFiles/Makefile2:843: dft/CMakeFiles/xc_itrf.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
```

**Comment by sunqm** [comment]
Is the libxc version 4.3.4?

**Comment by chchang6** [comment]
Ahh, indeed no, and I see the prereq now. Thanks
