### ISSUE TITLE
two-electron integral in real space

### ISSUE THREAD

**Issue by hungpham2017** [sunqm/pyscf#160]
Hello,
I am looking for the 2-electron integral in **real space** for the pbc-scf, similar to its **reciprocal-space** counterpart which can be accessed via the **pbc.scf.with_df.get_ao_eri** function.

Thank you

**Comment by pulkin** [comment]
Does anything stop you from constructing a supercell (maybe, even omitting unused atoms) and using a non-pbc `Mole.intor`? You may also reverse-engineer stuff by calculating the needed integral at a bunch of k-points and Fourier-transforming it (though, I believe, this is problematic without screening).

**Comment by sunqm** [comment]
``mol.intor('int2e')`` computes the Coulomb integrals in real space, without the lattice summation.

**Comment by hungpham2017** [comment]
I think `cell.intor('int2e')` will give me the eri for the reference cell as a 'molecule'.
Actually, I need the g_{p,q,r,s}^{0,L_1,L_2,L_3}  that is consistent with its reciprocal space counterpart.
I think I will try the inverse-FFT from the G-space eri(kk,kl,km,kn) as @pulkin mentioned.
thank you

**Comment by gkc1000** [comment]
Do you want p, q, r, s to be AO's, or crystalline AO's?

**Comment by hungpham2017** [comment]
I need the p, q, r, s are AO's and 0,L_1,L_2,L_3 indicate the reference cell (p) and translational vectors to the cells that contain q, r, s AOs.

**Comment by gkc1000** [comment]
Can you afford just to make a supercell?

You can make a supercell with the supercell function in

https://github.com/sunqm/pyscf/blob/master/pyscf/pbc/tools/pbc.py

Then with this supercell (treating it like a molecule) you can generate all
the ERI's for AO's within the supercell using cell.intor('...').

However, in your email, you write that you want an integral "that is
consistent with its reciprocal space counterpart". I don't know what you
precisely mean, how do you want to define your integral? I can imagine
several definitions compatible with the above statement.

**Comment by hungpham2017** [comment]
As far as I understand, the total energy in a PBC-PySCF calculation is computed by integrating over the Brillouin zone, hence the hcore(k), J(k), K(k) are needed.
I simply would like to recompute all these terms from hcore and ERI in the real space instead. By 'consistent' I meant the total energy for the reference cell calculated using these real-space quantities should be equal to that calculated in the G-space.
I have concerned that usually the Brillouin zone is sampled using a truncated k-mesh (not necessarily equal to the number of translation vectors used in the FFT). So I think an inverse-FFT may be helpful in this case.

**Comment by gkc1000** [comment]
I think you want to take Coulomb integrals of the isolated (i.e. non periodized) Gaussian functions, i.e. (pq|rs) and trace them with some kind of density matrix, in order to obtain J and K. In fact, this is what is done when computing the one-electron terms in the Hamiltonian: we sum over all the AO integrals, e.g. \sum_L (p0|qL), where L is a lattice vector. However, for the electronic Coulomb term, this lattice sum is divergent (the divergent part must be handled together with the electron-nuclear and nuclear-nuclear terms). In addition, you would need to consider the density matrix repeated out to infinite lattice separations.

The most direct way to define periodic quantities so they appear analogous to the molecular quantities is via the crystalline atomic orbitals. Then, one only needs to use the density matrix within the computational (supercell) and crystalline AO orbital integrals within the same supercell (with the divergent part removed) to compute J and K. This is what is done in PySCF.

**Comment by gkc1000** [comment]
If there is no other question, I will close this issue shortly.

**Comment by hungpham2017** [comment]
I am sorry for my late response. You answered my question. It is true that I would like to trace (pq|rs) with some density matrix (repeat in in lattice). I actually have been working on transforming (using the inverse-FFT) the reciprocal space (pq|rs) and k-dependent density matrix to real space, so the number of cell in real space will equal to the number of k-point, and that the energy calculated from there real space quantities should be consistent with the reciprocal space sampling. 
In fact, the tracing density matrix with hcore in real space gave me exactly the one calculated in k-space. for two-electron terms, it is a bit tricky (to me). I am planning to post an example here after I get it done so that someone may find it useful.

Thank you very much for your help. I'll reopen it again when I have something to update.

**Comment by jackbaker1001** [comment]
@hungpham2017  Did you get around to providing an example for the two-electron terms? I am dealing with a similar problem where I would like to calculate the coulomb energy using the ERIs and 1RDMs in reciprocal space.

**Comment by hungpham2017** [comment]
> @hungpham2017 Did you get around to providing an example for the two-electron terms? I am dealing with a similar problem where I would like to calculate the coulomb energy using the ERIs and 1RDMs in reciprocal space.

@jackbaker1001 it has been a while.But if only for debugging purpose, then you can FFT the k-point ERI to real space something similar to this: https://github.com/hungpham2017/pDMET/blob/dev/pdmet/localbasis.py#L232
