### ISSUE TITLE
[Question][Feature-Request] Dump all info for scf iterations?

### ISSUE THREAD

**Issue by ecurtin2** [sunqm/pyscf#163]
Hello, 

I was digging around the library and it seems like you can't currently get information about the scf iterations dumped into the chkfile. Is there actually a way to do this? 

Right now I've hacked my own way to do this into my local copy of `pyscf/scf/hf.py` where I basically wrote the following into the middle of the scf iterations:

```python
import h5py
import numpy as np
f = h5py.File(mf.chkfile)
try:
    group = f.create_group('iterations')
except ValueError:
    group = f['iterations']
subgroup = group.create_group('iteration_{}'.format(cycle))
subgroup.create_dataset('density_matrix', data=np.asarray(dm))
subgroup.create_dataset('density_matrix_norm', data=norm_ddm)
subgroup.create_dataset('total_energy', data=e_tot)
subgroup.create_dataset('mo_coefficients', data=mo_coeff)
subgroup.create_dataset('mo_energies', data=mo_energy)
subgroup.create_dataset('mo_occupancies', data=mo_occ)
subgroup.create_dataset('fock_matrix', data=fock)
f.close()
```
Here's what it looks like:

![selection_001](https://user-images.githubusercontent.com/20211309/37002026-f6fcbd84-208d-11e8-90d9-9a9d1d5806cd.png)

I figured since I struggled a bit to try to find out how to do this maybe it would benefit others to be able to do it as well? I'd think since the memory is already being used and hdf5 is the backend it shouldn't really cost anything to just dump this into a chkfile. 

-Evan

**Comment by sunqm** [comment]
SCF class has a hook for writing out all information in the SCF iterations. I add an example for this callback interface:  https://github.com/sunqm/pyscf/blob/master/examples/scf/24-callback.py

In case anyone needs the similar functionalities in CASSCF calculation, https://github.com/sunqm/pyscf/blob/master/examples/mcscf/24-callback.py  is a similar example that shows how to save the CASSCF orbitals in each step.

**Comment by ecurtin2** [comment]
Thanks! I tweaked your example for my use case and I'll put it here in case anybody else sees this and wants it:

```python

import pyscf

def checkpoint_iterations(
    mf, 
    env_vars=('fock', 'dm', 'norm_ddm', 'mo_occ', 'mo_coeff', 'mo_energy', 'e_tot'),
    rename=None
    ):
    """Wraps mf to dump iteration information to its chkfile.

    :param mf: Mean field object
    :param env_vars: The names of the environment variables to save.
    :param rename: Dictionary to rename the env variables in the save file. 
    Defaults to no renaming.

    Usage:

    >>> mol = pyscf.gto.M(atom='O 0 0 0; O 0 0 1.2', basis='sto-3g')
    >>> rhf = pyscf.scf.RHF(mol)
    >>> rhf.chkfile = 'test.hdf5'
    >>> rhf = checkpoint_iterations(rhf, rename={'fock': 'Fock Matrix'})
    >>> rhf.kernel()

    Results in all default env_vars being saved to 'test.hdf5' for each scf iteration
    and the fock matrix is stored under the name 'Fock Matrix'.
    """

    def save_scf_iteration(envs):
        cycle = envs['cycle']
        names = {}
        for var in env_vars:
            newname = rename.get(var)
            if newname is None:
                names[var] = var
            else:
                names[var] = newname

        info = {names[var]: envs[var] for var in env_vars}
        pyscf.scf.chkfile.save(mf.chkfile, 'Iterations/%d' % cycle, info)

    mf.callback = save_scf_iteration
    return mf
```
