### ISSUE TITLE
RHF vs UHF: H2 dissociation

### ISSUE THREAD

**Issue by mibumi** [sunqm/pyscf#167]
Hey,
I saw you had an scf-package example to calculate H2 dissociation using RHF, which I thought was a nice idea, so I took it a little step further and additionally calculated it using UHF (and plotted the results using matplotlib).
I added my code at the end here, so you can see.
I expected to see the typical overestimation of the dissociation energy with RHF at larger distances, due to lacking coulomb correlation and resulting ionic-like behavior of the separated H2 (while I expected UHF to give more accurate results in this case). 
However, as you can see, if you execute my code there is no difference for the longest time and after some distance RHF actually stops converging.
I am not sure, if I made a mistake & I sincerely hope this is not a stupid question, but I am confused as to why this is the case.

thank you :)

`import matplotlib.pyplot as plt
from pyscf import gto, scf

# define and build molecule:
mol = gto.Mole()
#mol.basis = "sto-3g"
#mol.basis = "ccpvdz"
mol.basis = "631g**"
mol.verbose = 3
mol.atom = [['H', (0.1, 0., 0.)], ['H', (0., 0., 0.)]]
mol = mol.build()

# define lists to store values for distance and energies:
xax = []  # rhf distances
yax = []  # rhf energies
xax_uhf = []  # uhf distances
yax_uhf = []  # uhf energies

# add first rhf element:
mf = scf.hf.RHF(mol)
mf.kernel()
xax.append(mol.atom[0][1][0])
yax.append(mf.e_tot)

# add first uhf element:
mf = scf.uhf.UHF(mol)
mf.kernel()
xax_uhf.append(mol.atom[0][1][0])
yax_uhf.append(mf.e_tot)

# add more elements:
for _ in range(0,30):
    x = mol.atom[0][1][0]
    x_new = x + 0.5
    mol.atom = [['H', (x_new, 0., 0.)], ['H', (0., 0., 0.)]]
    mol = mol.build()
    # RHF
    mf = scf.hf.RHF(mol)
    mf.kernel()
    xax.append(x_new)
    yax.append(mf.e_tot)
    # UHF
    mf = scf.uhf.UHF(mol)
    mf.kernel()
    xax_uhf.append(x_new)
    yax_uhf.append(mf.e_tot)
   
# plot it:
plt.plot(xax,yax) 
plt.plot(xax_uhf,yax_uhf)
plt.show()`

**Comment by gkc1000** [comment]
Hi Mibumi,

For UHF you will have to break the symmetry of the initial guess. See

https://github.com/sunqm/pyscf/blob/master/examples/scf/32-break_spin_symm.py

**Comment by mibumi** [comment]
Hi,

thank you so much, I made that small change and now it works.
