### ISSUE TITLE
[Question] Is it possible to access the ERI tensor?

### ISSUE THREAD

**Issue by replatero** [sunqm/pyscf#173]
Hi,

In the documentation for mean-field methods, it talks about caching the two-electron integrals but I want to access this tensor and use it for something else. I know that generally it is not recommended to work with the tensor directly but if I am only working with small molecules and want to access the _eri array, is it possible for me to do this?

I tried seeing if it was directly accessible after building an SCF object
``mf = scf.hf.SCF(mol)``
but after attempting to display the shape of _eri, I simply get None.

-Raul Platero

**Comment by sunqm** [comment]
It is also affected by the "max_memory" attribute.  By default, the maximum memory size is 4 GB. When the system has more than 250 orbitals, integrals will not be cached. Two options:

1. to increase the memory size, by setting "mol.max_memory = 10000" (10 GB, unit is MB). It can also be controlled by the environment variable "PYSCF_MAX_MEMORY")
2. set mol.incore_anyway = True.  This will force _eri being cached. If the system memory is not enough, the calculation will crash.

**Comment by replatero** [comment]
After trying both of these methods, I am still getting None. 
Here is what I am trying:
`mol = gto.M(atom = 'H 0 0 0; F 0 1 1.1')
mol.max_memory = 10000
#mol.incore_anyway = True

mf = scf.hf.SCF(mol)
mf.kernel()
print(mf._eri)`

Maybe I am doing something else incorrectly.

**Comment by sunqm** [comment]
```
mol = gto.M(atom = 'H 0 0 0; F 0 1 1.1')
mol.max_memory = 10000
#mol.incore_anyway = True

mf = scf.RHF(mol)
mf.kernel()
print(mf._eri)
```

If what you need is to access the 2-electron integrals, it's recommended to call the integral evaluation function:
eri = mol.intor('int2e')
eri = mol.intor('int2e', aosym='s8')  # 8-fold symmetry

It is not safe to access the internal data mf._eri since it may be changed in the future
