### ISSUE TITLE
[Question] Is it possible to get V_xc(r)?

### ISSUE THREAD

**Issue by RandomDefaultUser** [sunqm/pyscf#174]
Hello,

I am currently testing the SCAN functional in an electronic structure code developed at my university and I was looking for an electronic structure code to compare my results to. I came across pyscf, which worked great for me so far. My problem now is that I would like to compare the exchange-correlation potential. With the other code I get V_xc as V_xc(r), i.e. evaluated on the whole grid, r being the coordinate in space. So far I found that in pyscf there exists a routine that gives back V_xc as a potential matrix with the dimensions of (Number of AO)x(Number of AO). Is there a way to transform this expression into V_xc(r) with a given grid?

Thanks for considering my request.
- Lenz Fiedler

**Comment by sunqm** [comment]
I believe this example shows what you need:
https://github.com/sunqm/pyscf/blob/master/examples/dft/31-xc_value_on_grid.py#L37

**Comment by RandomDefaultUser** [comment]
Thank you for your answer!
I have looked into this example. I have investigated the dft.libxc.eval_xc() function with

```!/usr/bin/env python
import numpy
from pyscf import gto, dft
from pyscf.dft import numint
from matplotlib.pyplot import * 
from mpl_toolkits.mplot3d import Axes3D
'''
Evaluate exchange-correlation functional and its potential on given grid
coordinates and visualization. Based on example 31. 
'''
mol = gto.M(
            verbose = 0,
            atom = '''N    0.    0.       -0.5
                      N    0.    0.        0.5 ''',
            basis = '6-31g')
mf = dft.RKS(mol)
mf.kernel()
dm = mf.make_rdm1()
# Use default mesh grids and weights

coords = mf.grids.coords
weights = mf.grids.weights
ao_value = numint.eval_ao(mol, coords, deriv=1)

# The first row of rho is electron density, the rest three rows are electron
# density gradients which are needed for GGA functional

rho = numint.eval_rho(mol, ao_value, dm, xctype='GGA')
print(rho.shape)

#
# Evaluate XC functional for user specified functional
#

exc, vxc = dft.libxc.eval_xc('SCAN,SCAN', rho)[:2]
# vxc has the dimension ( 4 x number of grid points)
# the way I understood it, the first index specifies 
# the partial derivatives of exc.
print numpy.shape(vxc)
# These partial derivatives are w.r.t. to the density,
# the reduced gradient of the density (=sigma in terms of libxc)
# the kinetic energy density tau and the laplacian of the density.
print 'v_rho'
print numpy.shape(vxc[0])
print 'v_sigma'
print numpy.shape(vxc[1])
print 'v_tau'
print numpy.shape(vxc[2])
print 'v_laplacian'
print numpy.shape(vxc[3])
print 'Grid'
print numpy.shape(mf.grids.coords)```

However, as far as I have understood it, this only gives back the partial derivatives of the exchange-correlation energies as given by LibXC. What I am looking for is 

![codecogseqn](https://user-images.githubusercontent.com/37868410/38083929-4e67ad2a-334b-11e8-8644-8dfa32605cc7.gif)

As shown in Ref. [1] on page 158 in eq. 8.12 this can in principle be calculated via the partial derivatives of exc. As far as I know, these partial derivatives is what libxc (and therefore the pyscf routine you mentioned) gives back. Eq.8.12. cannot be used directly, as stated by Ref. [1], so I am assuming that pyscf is using Eq. 8.14 to construct a potential matrix using the direct application of the differential operators and partial derivatives given by Libxc to the KS equations. My question would now be if there is an instrinsic way in pyscf to transform <psi_j|V_xc|psi_i> into V_xc(r) using the grid and density matrix. As this is not needed for DFT calculations I am not sure whether or not it has been included in the code. 


[1] Martin, Richard M. Electronic structure: basic theory and practical methods. Cambridge university press, 2004.

**Comment by gkc1000** [comment]
To be clear, you cannot transform <psi_j|V_xc|psi_i> into V_xc(r) because
|psi_i> is in general not a complete basis.

I do not know if there is a convenience function to return vxc(r) anywhere,
but as you point out, you can reassemble vxc from the partial derivatives
of
exc via some simple formulae and this is what is done when
<psi_j|V_xc|psi_i> is made. For example in  function "eval_mat" in

line 385:
https://github.com/sunqm/pyscf/blob/dev/pyscf/dft/numint.py

you can see the construction of vxc for a GGA in lines 460:461. There is a
private function, _rks_gga_wv0 (line 1172) which
does the same thing.

On Thu, Mar 29, 2018 at 6:40 PM, RandomDefaultUser <notifications@github.com

**Comment by sunqm** [comment]
Given the matrix elements <psi_i|V_xc|psi_j> and the basis functions psi_i and psi_j, I think there are many possible V(r) that give the same V_xc matrix elements.  For example, the code below can give one type of V(r)

s = mol.intor('int1e_ovlp')
s_inv = numpy.linalg.inv(s)
ao = mol.eval_gto('GTOval',  mf.grids.coords)

v = s_inv.dot(vxc_matrix).dot(s_inv)
v_r = numpy.einsum('pi,pi->p', ao.dot(s), ao)

But I would not assume this V(r) faithfully reflects V_xc(r).

**Comment by RandomDefaultUser** [comment]
Thanks to everyone for their time and answers.
I think "To be clear, you cannot transform <psi_j|V_xc|psi_i> into V_xc(r) because
|psi_i> is in general not a complete basis." pretty much verifies my assumption that what I am looking for is not as easily available. I will try to work on a different way of testing Vxc.
