### ISSUE TITLE
Scalar relativistic correction

### ISSUE THREAD

**Issue by huuco** [sunqm/pyscf#18]
Hello,

I have a small question about the scalar relativistic correction. It is not clear which scalar relativistic correction method is included in the code. Will DHK scalar relativistic be implemented in future?

Thanks.

**Comment by sunqm** [comment]
Hi Thomas,

It has X2Cmethod, see eg http://www.tandfonline.com/doi/abs/10.1080/00268971003781571

There is an example to call X2C:  https://github.com/sunqm/pyscf/blob/1.0/examples/scf/21-x2c.py

**Comment by huuco** [comment]
Dear Qiming,

Thank you for your answer.
