### ISSUE TITLE
Extract density matrix from pbc 1d calculation

### ISSUE THREAD

**Issue by bsonghao** [sunqm/pyscf#185]
Hello
I am trying to do something implantation works
from pyscf pbc library and I need to extract the
1-electron density matrix from 1d  solid state 
calculation. I wonder how can I do that?

**Comment by sunqm** [comment]
If you are running pbc-scf method, regardless whether it's 3D or 1D system, you can call .make_rdm1() method of the mean field object.  It returns the density matrix in AO representation. E.g.
```
cell = ...
kmf = pbc.dft.KRKS(cell, cell.make_kpts([2,2,2]).run()
dm1 = kmf.make_rdm1()
```
 If the method is MP2, CISD, CCSD, .make_rdm1() method is also available https://github.com/sunqm/pyscf/blob/dev/examples/pbc/22-k_points_ccsd.py#L63 . The basis for density matrix is MO basis.

**Comment by bsonghao** [comment]
Thanks. Is the density matrix stored in real space or reciprocal space? 
And I also need the 1-electron overlap matrix. How can I do that?

Songhao

**Comment by bsonghao** [comment]
I tried to run 1d H2 calculation solid with 11 kpoints and printed
 the 1e density matrix and its shape:
[[[0.53706191+0.00000000e+00j 0.53706191-8.70972946e-18j]
  [0.53706191+8.70972946e-18j 0.53706191+0.00000000e+00j]]

 [[0.55339471+0.00000000e+00j 0.55339471+7.33078634e-17j]
  [0.55339471-7.33078634e-17j 0.55339471+0.00000000e+00j]]

 [[0.60193786+0.00000000e+00j 0.60193786-4.71952054e-17j]
  [0.60193786+4.71952054e-17j 0.60193786+0.00000000e+00j]]

 [[0.67835755+0.00000000e+00j 0.67835755+2.25582959e-17j]
  [0.67835755-2.25582959e-17j 0.67835755+0.00000000e+00j]]

 [[0.76578082+0.00000000e+00j 0.76578082-3.25743413e-17j]
  [0.76578082+3.25743413e-17j 0.76578082+0.00000000e+00j]]

 [[0.82815377+0.00000000e+00j 0.82815377+1.15015674e-16j]
  [0.82815377-1.15015674e-16j 0.82815377+0.00000000e+00j]]

 [[0.82815377+0.00000000e+00j 0.82815377+1.63104315e-16j]
  [0.82815377-1.63104315e-16j 0.82815377+0.00000000e+00j]]

 [[0.76578082+0.00000000e+00j 0.76578082-1.07304770e-16j]
  [0.76578082+1.07304770e-16j 0.76578082+0.00000000e+00j]]

 [[0.67835755+0.00000000e+00j 0.67835755+2.25523226e-17j]
  [0.67835755-2.25523226e-17j 0.67835755+0.00000000e+00j]]

 [[0.60193786+0.00000000e+00j 0.60193786+1.10885822e-17j]
  [0.60193786-1.10885822e-17j 0.60193786+0.00000000e+00j]]

 [[0.55339471+0.00000000e+00j 0.55339471-1.30561231e-17j]
  [0.55339471+1.30561231e-17j 0.55339471+0.00000000e+00j]]]
(11, 2, 2)
I assumed that it is in k space and what's your order  of your k-points?
I need to transfer it into real space.

**Comment by gkc1000** [comment]
import numpy as np
dmR=np.einsum("kij->ij",kmf.make_rdm1()

**Comment by bsonghao** [comment]
thanks
