### ISSUE TITLE
Bug: simple pbc-tddft calculation crashed

### ISSUE THREAD

**Issue by tzyii** [sunqm/pyscf#186]
from pyscf.pbc import gto 
from pyscf.pbc import scf 
from pyscf.pbc import df
from pyscf.pbc import tddft
cell = gto.Cell()
cell.unit = 'B' 
cell.atom = ''' 
C  0.          0.          0.        
C  1.68506879  1.68506879  1.68506879
'''
cell.a = ''' 
0.          3.37013758  3.37013758
3.37013758  0.          3.37013758
3.37013758  3.37013758  0.
'''
cell.basis = 'gth-szv'
cell.pseudo = 'gth-pade'
cell.gs = [12]*3
cell.build()
mf = scf.KRHF(cell, cell.make_kpts([2,1,1])).set(exxdiv=None)
mf.run()
td = tddft.rks.TDA(mf)
td.verbose = 5 
print(td.kernel()[0] * 27.2114)
td = tddft.rks.TDHF(mf)
td.verbose = 5 
print(td.kernel()[0] * 27.2114)

  File "~/.local/opt/Miniconda/lib/python3.6/site-packages/pyscf/pbc/tdscf/rhf.py", line 235, in _get_eai
    ai = lib.direct_sum('a-i->ai', mo_energy[k,viridx], mo_energy[k,occidx])
TypeError: list indices must be integers or slices, not tuple

mo_energy is a not a ndarray in _get_eai function in rhf.py.

**Comment by gkc1000** [comment]
TDDFT does not yet support k-pts. You can use TDDFT with PBC without kpts (i.e. a supercell calculation). Methods which support kpts typically have a "K" prefix, e.g. KRHF, KRCCSD, etc.

**Comment by tzyii** [comment]
import numpy
from pyscf.pbc import gto, scf 

cell = gto.M(
    a = numpy.eye(3)*3.5668,
    atom = '''C     0.      0.      0.    
              C     0.8917  0.8917  0.8917
              C     1.7834  1.7834  0.    
              C     2.6751  2.6751  0.8917
              C     1.7834  0.      1.7834
              C     2.6751  0.8917  2.6751
              C     0.      1.7834  1.7834
              C     0.8917  2.6751  2.6751''',
    basis = '6-31g',
    verbose = 4,
)

mf = scf.RHF(cell).density_fit()
mf.with_df.gs = [5]*3
mf.kernel()

#
# Import CC, TDDFT moduel from the molecular implementations
#
from pyscf import cc, tddft

mytd = tddft.TDHF(mf)
mytd.nstates = 5 
mytd.kernel()

Is this calculation wrong? It failed again. 

******** <class 'pyscf.pbc.df.df.GDF'> flags ********
mesh = [10 10 10] (1000 PWs)
auxbasis = None
eta = 0.23178468164192328
_cderi_to_save = ~/tmpuwipyibm
len(kpts) = 1
Drop 24 primitive fitting functions
make aux basis, num shells = 168, num cGTOs = 488
auxcell.rcut 10.13177881352399
init E= -312.237317613867
  HOMO = 0.642832522451155  LUMO = 0.848569289894313
cycle= 1 E= -302.686584799308  delta_E= 9.55  |g|= 0.349  |ddm|= 5.22
  HOMO = 0.344591260068089  LUMO = 0.948669025492524
cycle= 2 E= -302.718879245823  delta_E= -0.0323  |g|= 0.0677  |ddm|= 1.08
  HOMO = 0.343481575002403  LUMO = 0.951484777967152
cycle= 3 E= -302.720257453631  delta_E= -0.00138  |g|= 0.00751  |ddm|= 0.253
  HOMO = 0.343519433477144  LUMO = 0.951493488673782
cycle= 4 E= -302.72027389823  delta_E= -1.64e-05  |g|= 0.00218  |ddm|= 0.0196
  HOMO = 0.343503975782633  LUMO = 0.951478154728212
cycle= 5 E= -302.720276412614  delta_E= -2.51e-06  |g|= 0.000423  |ddm|= 0.0119
  HOMO = 0.343479163902551  LUMO = 0.951491446668659
cycle= 6 E= -302.720276622827  delta_E= -2.1e-07  |g|= 0.000177  |ddm|= 0.0047
  HOMO = 0.343483161348929  LUMO = 0.951501238611588
cycle= 7 E= -302.720276679443  delta_E= -5.66e-08  |g|= 7.07e-05  |ddm|= 0.00314
  HOMO = 0.343483005192155  LUMO = 0.951506785979993
cycle= 8 E= -302.720276688846  delta_E= -9.4e-09  |g|= 1.65e-05  |ddm|= 0.0016
  HOMO = 0.343482177263842  LUMO = 0.951507624183928
cycle= 9 E= -302.720276689232  delta_E= -3.87e-10  |g|= 4.7e-06  |ddm|= 0.000316
  HOMO = 0.343482251924166  LUMO = 0.951507666305303
Extra cycle  E= -302.720276689255  delta_E= -2.24e-11  |g|= 2.73e-06  |ddm|= 3.43e-05
converged SCF energy = -302.720276689255


******** <class 'pyscf.tdscf.rhf.TDHF'> for <class 'pyscf.pbc.scf.hf.RHF'> ********
nstates = 5 singlet
wfnsym = None
conv_tol = 1e-09
eigh lindep = 1e-12
eigh level_shift = 0
eigh max_space = 50
eigh max_cycle = 100
chkfile = ~/tmpuaajv1g1
max_memory 4000 MB (current use 201 MB)


Traceback (most recent call last):
  File "./a.py", line 37, in <module>
    mytd.kernel()
  File "~/.local/opt/Miniconda/lib/python3.6/site-packages/pyscf/tdscf/rhf.py", line 894, in kernel
    verbose=log)
  File "~/.local/opt/Miniconda/lib/python3.6/site-packages/pyscf/lib/linalg_helper.py", line 759, in davidson_nosym1
    de = e - elast
ValueError: operands could not be broadcast together with shapes (4,) (5,)

**Comment by sunqm** [comment]
The error is due to the numerical issue when diagonalizing a non-hermitian matrix. I don't have a good solution for this problem so far. You can consider to use TDA approximation which should be working.

For the k-point tddft, I have upgraded the implementation.  However, you will basically observe similar numerical problems.  The diagonalization procedure often stops early before converging for problems like linear dependence and others.  It will be difficult to converge TDHF or TDDFT.

**Comment by tberkel** [comment]
I've found that this can sometimes be alleviated by just iterating again.
The actual error is just because of a size mismatch after a _qr() removes a
linearly independent trial vector (I think).  But if you just consider that
step unconverged and iterate again, I have seen it recover.  What do you
think Qiming?

-- 
Timothy C. Berkelbach
Neubauer Family Assistant Professor
Department of Chemistry and James Franck Institute
The University of Chicago

929 E. 57th Street, GCIS E133, Chicago, IL 60637
Cell: 917-446-2687
Office: 773-834-9879
E-mail: berkelbach@uchicago.edu
Web: berkelbachgroup.uchicago.edu

**Comment by tzyii** [comment]
The test works well with TDA approximation. Thanks a lot!
