### ISSUE TITLE
Frozen core for NEVPT2

### ISSUE THREAD

**Issue by huuco** [sunqm/pyscf#19]
Hi,

Correct me if I am wrong, there is no frozen core option for NEVPT2. I can only find the frozen core option for the CCSD and MCSCF modules.

Best
Thomas

**Comment by sunqm** [comment]
Frozen core is not available for NEVPT2.  I'll consider this feature when optimizing NEVPT2 in the future.

**Comment by jagunther** [comment]
The NEVPT2 method prints the eight contributions to the second order energy correction, e.g.
```
Sr    (-1)',   E = -0.09815626499877
Si    (+1)',   E = -0.00002355594769
Sijrs (0)  ,   E = -0.02394811313138
Sijr  (+1) ,   E = -0.00056142061480
Srsi  (-1) ,   E = -0.01137603732026
Srs   (-2) ,   E = -0.30714701720375
Sij   (+2) ,   E = -0.00001148262247
```
and each contribution corresponds to one class of occupations in core and virtual space (I assume PySCF is following the notation of [https://doi.org/10.1063/1.1515317)](https://doi.org/10.1063/1.1515317)).
Only Sr(-1) and Srs(-2) involve excitations that leave the core electrons untouched, so I would say the sum of Sr(-1) and Srs(-2) should be the NEVPT2 energy correction in the frozen core approximation. Is that right?

**Comment by bogdanoff** [comment]
That is true if you want to freeze *all* the inactive orbitals (aka core).

In most practical cases, however, one wants to freeze some number of non-relevant (like deep-core 1s) orbitals to make calculations faster/cheaper.
