### ISSUE TITLE
TDDFT oscillator strength and NTO

### ISSUE THREAD

**Issue by wen-xl** [sunqm/pyscf#191]
Hi,

I'm running singlet TDDFT calculations on chromophore to find out bright states, and I found that the "get_nto" and "oscillator_strength" functions in tdscf.rhf are almost done in the latest version 1.5. Is the code working correctly so that I could simply replace the "tdjob" with the respective variable to run it? If not, will they be fully functional in next update?

Thanks

**Comment by sunqm** [comment]
Yes, nto and analysis for tddft amplitudes are functionalized.

**Comment by sunqm** [comment]
Here is the example of NTO analysis.

https://github.com/sunqm/pyscf/blob/master/examples/tddft/01-nto_analysis.py
