### ISSUE TITLE
symm.addons.symmetrize_space erroneous orthonormality check?

### ISSUE THREAD

**Issue by MatthewRHermes** [sunqm/pyscf#198]
On symm/addons.py on line 196, the function symmetrize_space attempts to make sure that the provided orbitals are orthonormal:

`assert(numpy.allclose(numpy.dot(mo.T.conj(), s_mo), numpy.eye(nmo)))`

But shouldn't it be

`assert(numpy.allclose(reduce (numpy.dot, (mo.T.conj(), s_mo, mo)), numpy.eye(nmo)))`

or something?  Isn't the expression **C'SC** = **1**?

**Comment by MatthewRHermes** [comment]
Damn, oops.  My problem appears to be just in the tolerance of that assert.  For a certain molecule, the MOs of a converged CASSCF calculation have ||**C**'**SC**-**1**|| = 5e-6.

**Comment by sunqm** [comment]
What is the system?  The normalization error ~ 5e-6 in CASSCF orbitals seems too large.  It maybe implies the linear dependence in the basis set.

Anyway, if you want to reduce the tolerance of the check, a keyword argument "tol" was added in that function.

**Comment by MatthewRHermes** [comment]
Minimal example:

`from pyscf import scf, mcscf, gto`
`import numpy as np`
`import scipy`
`from functools import reduce`

`mol = gto.M (atom = '''H   1.1144663046812031   4.8526120091140630  -0.0000009231233643`
`N   0.0679752085161149   4.7568470134832737   0.0000000899251747`
`N  -0.8321028497545504   1.6340592092970057   0.0000000430531684`
`C   0.1741885861827601   0.6488246445362962   0.0000000099209304`
`H   1.2254312883380023   0.9533981643165998   0.0000010007946515`
`C  -0.1741885861827601  -0.6488246445362962  -0.0000000099209304`
`H  -1.2254312883380023  -0.9533981643165998  -0.0000010007946515`
`N   0.8321028497545504  -1.6340592092970057  -0.0000000430531684`
`N  -0.0679752085161149  -4.7568470134832737  -0.0000000899251747`
`H  -1.1144663046812031  -4.8526120091140630   0.0000009231233643''',`
`    basis='6-31g', symmetry=True, spin=0)`

`mf = scf.RHF (mol)`
`mf.kernel ()`
`mc = mcscf.CASSCF (mf, 10, 10)`
`mc.kernel (mcscf.addons.sort_mo_by_irrep (mc, mf.mo_coeff, {'Ag': 2, 'Bg': 3, 'Au': 3, 'Bu': 2}))`
`olap_norm = scipy.linalg.norm (`
`    reduce (np.dot, (mc.mo_coeff.conjugate ().T, mf.get_ovlp (), mc.mo_coeff))`
`    - np.eye (mc.mo_coeff.shape[1]))`
`print ("Error from orthonormal orbital norm: {}".format (olap_norm))`

yields:

`converged SCF energy = -294.679223380369`
`CASSCF energy = -295.535062031175`
`CASCI E = -295.535062031175  E(CI) = -13.8674839496427  S^2 = 0.7319425`
`Error from orthonormal orbital norm: 5.4361711873369035e-06`

This came from a potential energy scan.  I noticed that if I rounded the z-coordinates to zero, I get a more reasonable

`converged SCF energy = -294.67922338037`
`CASSCF energy = -295.535060154051`
`CASCI E = -295.535060154051  E(CI) = -13.8674864485155  S^2 = 0.8447664`
`Error from orthonormal orbital norm: 4.342948637585964e-14`

Does this have something to do with a molecule being almost, but not quite planar?

**Comment by sunqm** [comment]
This is because the molecule does not have the strict C2h symmetry while the orbitals are the strictly symmetry-adapted orbitals.  The symmetry module has small error tolerance (~1e-5) on the geometry. You can switch off the tolerance before initializing the Mole object

from pyscf import symm
symm.geom.TOLERANCE = 0
