### ISSUE TITLE
wrong eom-ccsd energies for open-shell reference 

### ISSUE THREAD

**Issue by fishjojo** [sunqm/pyscf#199]
sample input as follows:

```
from pyscf import gto,scf,cc
import numpy

mol = gto.M(atom='O 0 0 0;H 0 0.78 -0.78; H 0 0 1.1', spin=2)
mol.basis = 'ccpvdz'
mol.symmetry = False
mol.build(verbose = 5)
mf = scf.UHF(mol)
mf.scf()

mycc = cc.UCCSD(mf)
mycc.kernel()
mycc.eomee_ccsd(4)
```
output energies are as follows:

> E(UCCSD) = -75.99324882036385
> EOM-CCSD root 0 E = 0.04414031579953943  qpwt = 0.939451  conv = True
> EOM-CCSD root 1 E = 0.1036046947840601  qpwt = 0.978899  conv = True
> EOM-CCSD root 2 E = 0.2109223996063989  qpwt = 0.539942  conv = True
> EOM-CCSD root 3 E = 0.2518781021802057  qpwt = 0.305218  conv = True

The same calculation by NWChem gives the same UCCSD energy but different excitation energies:

>  CCSD total energy / hartree       =       -75.993248837113669
>  Excited state root  1
>  Excitation energy / hartree =        0.035507922057598
>  Excited state root  2
>  Excitation energy / hartree =        0.102790937034369
>  Excited state root  3
>  Excitation energy / hartree =        0.204806698436480
>  Excited state root  4
>  Excitation energy / hartree =        0.247420373226294

QChem gives the same results as NWChem, so it's very likely that the Pyscf results are wrong.
And uccsd.eomsf_ccsd has the same problem.

The results for spin=0 case are correct.

**Comment by gkc1000** [comment]
As this bug has been fixed, I'm closing this issue.
