### ISSUE TITLE
Manually set molecular symmetry in SCF

### ISSUE THREAD

**Issue by wirawan0** [sunqm/pyscf#2]
Hi Qiming,

Can we manually set the symmetry of a molecule in the SCF/HF module? Say, if the molecule has D2h symmetry but I want it to be C2v instead--for breaking symmetry in UHF.

Wirawan

**Comment by sunqm** [comment]
No, I didn't implement that code.

Qiming
On Mon, Jan 12, 2015 at 08:13:24AM -0800, Wirawan Purwanto wrote:
> Hi Qiming,
> 
> Can we manually set the symmetry of a molecule in the SCF/HF module? Say, if
> the molecule has D2h symmetry but I want it to be C2v instead--for breaking
> symmetry in UHF.
> 
> Wirawan
> 
> —
> Reply to this email directly or view it on GitHub.*
> 

-- 
Dr. Qiming Sun
Frick Chemistry Laboratory
Princeton University
www.sunqm.net
