### ISSUE TITLE
how to get fci wavefunction after pyscf.fci.FCI

### ISSUE THREAD

**Issue by yuhanzheng1** [sunqm/pyscf#20]
Hello! I want to get fci wavefunctions after pyscf.fci.FCI, and I refer to your code in '#1293''example/ci/20-from_fci.py'.  However I still can‘t  get wavefunctions correctly.(maybe I didn't do it the right way ). Do you know how to get them after getting cis_a, cis_b, cid_aa and so on.  Thank's a lot if you share me the code about it!

**Comment by sunqm** [comment]
Duplicated to https://github.com/pyscf/pyscf/issues/1522
