### ISSUE TITLE
examples fail

### ISSUE THREAD

**Issue by MJech** [sunqm/pyscf#20]
Hi all,

I recently downloaded PySCF package. I wanted to start with some of the provided examples, but it seems that most of them fail?! 
For example UHF does not work at all, I always get the error: 
AttributeError: 'UHF' object has no attribute 'level_shift'
Other examples fail because there is no newton-module.

Did I miss anything? Simple RHF calculations work, I guess the installation worked. I downloaded the (I guess latest version) from github, as suggested in the tutorial.

Cheers,
 Markus

**Comment by gkc1000** [comment]
Hi Markus,

Please download the release branch "v1.0", not the branch "master", which
is the development branch.

Garnet

**Comment by MJech** [comment]
Hi Garnet,

thanks, but it did not help, I guess I already had the v1.0 release and not the master branch .... I get the exact same errors!!

Cheers,
Markus

**Comment by gkc1000** [comment]
Ok. We will mark as a regression and fix.

**Comment by sunqm** [comment]
Newton solver is not available in version 1.0.  Please checkout master branch to use it.  The master branch will move to 1.1 branch recently.

Best,
Qiming
