### ISSUE TITLE
Apparent nondeterminism in scf._vhf.direct

### ISSUE THREAD

**Issue by MatthewRHermes** [sunqm/pyscf#201]
I'm trying to track down a source of non-deterministic behavior which is causing my code to sometimes yield qualitatively different results for repeated execution of the same calculation.  Is there a known quasirandom step in the RHF and CASSCF algorithms?  The earliest appearance of nondeterministic behavior (at a very small mangitude) seems to be the calculation of the effective potential and apparently the function scf._vhf.direct, which is called by scf.hf.get_jk and scf.hf.get_veff:

`from pyscf import gto, scf`
`import numpy as np`

`mol = gto.M (atom = '''C 0.0 0.0 0.0`
`                       O 1.16 0.0 0.0`
`                       O -1.16 0.0 0.0''', `
`                basis='6-31g', spin=0)`
`mf = scf.RHF (mol)`
`mf.verbose = 0`

`dm0 = mf.get_init_guess ()`
`nao = dm0.shape[-1]`
`vj0, vk0 = scf._vhf.direct(dm0.reshape(-1,nao,nao), mol._atm, mol._bas, mol._env, `
`    vhfopt=None, hermi=1, cart=mol.cart)`
`vj1, vk1 = scf._vhf.direct(dm0.reshape(-1,nao,nao), mol._atm, mol._bas, mol._env, `
`    vhfopt=None, hermi=1, cart=mol.cart)`
`vj2, vk2 = scf._vhf.direct(dm0.reshape(-1,nao,nao), mol._atm, mol._bas, mol._env, `
`    vhfopt=None, hermi=1, cart=mol.cart)`
`print ("||vj0 - vj1|| = {}".format (np.linalg.norm (vj0 - vj1)))`
`print ("||vk0 - vk1|| = {}".format (np.linalg.norm (vk0 - vk1)))`
`print ("||vj0 - vj2|| = {}".format (np.linalg.norm (vj0 - vj2)))`
`print ("||vk0 - vk2|| = {}".format (np.linalg.norm (vk0 - vk2)))`
`print ("||vj1 - vj2|| = {}".format (np.linalg.norm (vj1 - vj2)))`
`print ("||vk1 - vk2|| = {}".format (np.linalg.norm (vk1 - vk2)))`

`mf.kernel (dm0=dm0)`
`assert (mf.converged)`
`e1 = mf.e_tot`
`mf.kernel (dm0=dm0)`
`assert (mf.converged)`
`e2 = mf.e_tot`
`mf.kernel (dm0=dm0)`
`assert (mf.converged)`
`e3 = mf.e_tot`
`print ("energy of first run  = {}".format (repr (e1)))`
`print ("energy of second run = {}".format (repr (e2)))`
`print ("energy of third run  = {}".format (repr (e3)))`

yields (the first time):

`||vj0 - vj1|| = 1.2948549968273146e-14`
`||vk0 - vk1|| = 2.747828726778302e-15`
`||vj0 - vj2|| = 1.3320483852938603e-14`
`||vk0 - vk2|| = 3.045532312882988e-15`
`||vj1 - vj2|| = 1.3418069281046381e-14`
`||vk1 - vk2|| = 3.3684841051112857e-15`
`energy of first run  = -187.5149486074269`
`energy of second run = -187.5149486074269`
`energy of third run  = -187.51494860742673`

The numbers differ on repeated executions.  See the [attached tarball](https://github.com/sunqm/pyscf/files/2156801/example.tar.gz).  Obviously this is a very small amount of non-determinism, but it seems to grow in my non-trivial DMET and CASSCF applications (up to 10^-5 Eh differences in energies of apparently qualitatively equivalent results, and some cases where I get qualitatively different results).  By contrast, the get_init_guess, get_ovlp, and get_hcore functions yield identical results on repeated calls and executions

.

**Comment by gkc1000** [comment]
Hi Matt - have you tried setting the number of threads to 1? OpenMP
parallelism is not strictly deterministic since FP arithmetic is not
commutative under rounding.

**Comment by MatthewRHermes** [comment]
Ah, OK.  Yes that does make the nondeterministic behavior go away, thank you.  There must be something in the DMET code that's unstable to small rounding errors.
