### ISSUE TITLE
install issue on cray-gnu

### ISSUE THREAD

**Issue by vamshimohank** [sunqm/pyscf#202]
Dear Qiming,

I am trying to install in cray-gnu environment. 
I followed the instructions in http://sunqm.github.io/pyscf/install.html#manual-installation-from-github-repo . After some issues with libxcfun and libxc (I had to install them separately and put them in pyscf/lib/deps/) the installation went fine.

Now when I try to test the installation,  I get the following error (see after this paragraph). It looks like the shared libraries are not being created for some reason. Everything used to work perfectly up to pyscf-1.4. 

Has something changed is the installation procedure? 

>>> import pyscf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/snx3000/katukuri/software/venv_python2.7/pyscf/pyscf/__init__.py", line 52, in <module>
    from pyscf import lib
  File "/scratch/snx3000/katukuri/software/venv_python2.7/pyscf/pyscf/lib/__init__.py", line 24, in <module>
    from pyscf.lib import numpy_helper
  File "/scratch/snx3000/katukuri/software/venv_python2.7/pyscf/pyscf/lib/numpy_helper.py", line 40, in <module>
    _np_helper = misc.load_library('libnp_helper')
  File "/scratch/snx3000/katukuri/software/venv_python2.7/pyscf/pyscf/lib/misc.py", line 63, in load_library
    return numpy.ctypeslib.load_library(libname, _loaderpath)
  File "/scratch/snx3000/katukuri/software/venv_python2.7/lib/python2.7/site-packages/numpy/ctypeslib.py", line 155, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension

**Comment by vamshimohank** [comment]
$ cd pyscf/lib
$ mkdir build
$ cd build
$ cmake ..
$ ccmake . (to switch of build xclib and xclibfun libraries)
$ make

thats how I try to build the c libraries as explained in the manual. 

What is surprising is that the libraries are not created in $PYSCFHOME/pyscf/pyscf/lib even though the make command exist successfully.  

I have also realised that this behaviour is specific to the CRAY-GNU environment. On other linux-clusters the build process works perfectly without any issues (the libraries are created in $PYSCFHOME/pyscf/pyscf/lib).

Regards
Vamshi

**Comment by sunqm** [comment]
Do you know what is the default C compiler on this CRAY-GNU cluster?

**Comment by vamshimohank** [comment]
Hi,

I think I figured out what the issue is. By default in CRAY-GNU environment, the compiler wrappers produce statically-linked executables by default; for dynamic libraries one should use the -dynamic flag or export CRAYPE_LINK_TYPE=dynamic before building.

This got changed during the last system update and maintenance I guess.  

Thanks anyways. 

Regards
Vamshi
