### ISSUE TITLE
Running mpi RHF/RKS calculations?

### ISSUE THREAD

**Issue by hungpham2017** [sunqm/pyscf#204]
I found the example of how to run a mpi-CCSD calculation. I wonder whether this MPI function supports mean-field calculation as well.
Thank you

**Comment by gkc1000** [comment]
Not yet for the molecular code/gamma point, only for k-pts.

**Comment by hungpham2017** [comment]
I really meant the k-pts rhf calculation. I couldn't find an example to to do that.

**Comment by hungpham2017** [comment]
oops! my bad. Thank you very much

**Comment by hungpham2017** [comment]
I ran the 01-parallel_krhf-diamond.py example usingn python3.4 and got this error
> Traceback (most recent call last):
> File "01-parallel_krhf-diamond.py", line 34, in 
> mf.with_df = df.FFTDF(cell, kpts)
> File "/panfs/roc/groups/6/gagliard/phamx494/mpi4pyscf/tools/mpi.py", line 498, in init
> (args[0].dumps(),)+args[1:], kwargs))
> File "/panfs/roc/groups/6/gagliard/phamx494/mpi4pyscf/tools/mpi_pool.py", line 133, in apply
> F = _function_wrapper(function)
> File "/panfs/roc/groups/6/gagliard/phamx494/mpi4pyscf/tools/mpi_pool.py", line 171, in init
> self.func_code = marshal.dumps(function.func_code)
> AttributeError: 'function' object has no attribute 'func_code'
