### ISSUE TITLE
How to access the CCSD density? 

### ISSUE THREAD

**Issue by RandomDefaultUser** [sunqm/pyscf#208]
Hello,

I am trying to reproduce the results given by [Perdew](http://science.sciencemag.org/content/355/6320/49) with PySCF. In the linked article, DFT densities are compared to CCSD densities. I figured I could recreate these results using PySCF, given that it allows for HF, DFT and CCSD calculations. My workflow reads:
1. Perform a DFT(LDA)/HF/CCSD calculation.
2. Use make_rdm1() of every class to create density matrices.
3. Process the results.

While I was successful for small atoms, I am currently struggling to get a correct density for the N2 molecule. In order to process the results (step 3) I tried:

- using the eval_ao / eval_rho routines.
- using the cubegen.density routine (I use PySCF in the dev branch)
- saving data to wfn files and processing it with [Mutliwfn](http://sobereva.com/multiwfn/)

A minimal working example is attached at the end of my post. While for N2 the DFT and HF density seem to be working just fine, the CCSD density appears to be incorrect. Both when investigating the .cube files with VESTA and when directly visualizing the densities produced by eval_rho, the CCSD density looks strange. The CCSD density is localized at one atom, which is clearly incorrect for N2. The attached pictures illustrate this odd behavior.
This is the density plot: 
![rho_plot](https://user-images.githubusercontent.com/37868410/43520743-0d429b42-9594-11e8-9a13-e44bd79ae4cc.png)
These are the cube files (HF, DFT, CCSD): 
![hf_density](https://user-images.githubusercontent.com/37868410/43520745-0d5fa82c-9594-11e8-926c-282b46f72ffe.png)
![dft_density](https://user-images.githubusercontent.com/37868410/43520747-0d80f9b4-9594-11e8-8aa7-cb25e212ff0a.png)
![ccsd_density](https://user-images.githubusercontent.com/37868410/43520749-0d9ba796-9594-11e8-87cb-e25e2179a41f.png)

My question now is: Am I accessing the CCSD density incorrectly? If so, how is this done right? Clearly my results are not what one would expect.

Thank you in advance for your time and comments. 

Minimal working example:

```
from pyscf import dft,gto,scf,cc
import numpy as np
from pyscf.tools import cubegen

# Create a Mole object.

mol = gto.M(
    verbose = 4,
    atom = '''
    N    0.    0.   0.54799639
    N    0.    0.   -0.54799639''',
    basis = 'ccpvdz')

# Peform a DFT calculation.

mf = dft.UKS(mol)
mf.max_cycle = 500
mf.conv_tol = 1e-8 
mf.grids.level = 3
mf.xc = 'LDA,PW'
mf.kernel()

# Calculate the DFT density on the grid.

ao = dft.numint.eval_ao(mol, mf.grids.coords, deriv=0)
dm_dft = mf.make_rdm1()
rho_dft_up = dft.numint.eval_rho(mol, ao, dm_dft[0], None, 'LDA', 0, None)
rho_dft_dn = dft.numint.eval_rho(mol, ao, dm_dft[1], None, 'LDA', 0, None)
rho_dft = rho_dft_up + rho_dft_dn

# Save the DFT density.

np.savetxt('rho_dft.dat',rho_dft)
mesh = mf.grids.coords
np.savetxt('mesh.dat',mesh) # Also save the Mesh data.

# Save the DFT density as cube files.

cubegen.density(mol, 'rho_dft_0.cube', dm_dft[0])
cubegen.density(mol, 'rho_dft_1.cube', dm_dft[1])

# Perform a HF calculation.

mf_scf = scf.UHF(mol)
mf_scf.conv_tol = 1e-14
mf_scf.kernel()
dm_hf = mf_scf.make_rdm1()

# Calculate the HF density on the grid.

rho_hf_up = dft.numint.eval_rho(mol, ao, dm_hf[0],  None, 'LDA', 0, None)
rho_hf_dn = dft.numint.eval_rho(mol, ao, dm_hf[1],  None, 'LDA', 0, None)
rho_hf = rho_hf_up + rho_hf_dn

# Save the HF density.

np.savetxt('rho_hf.dat',rho_hf)

# Save the HF density as cube files.

cubegen.density(mol, 'rho_hf_0.cube', dm_hf[0])
cubegen.density(mol, 'rho_hf_1.cube', dm_hf[1])

# Perform a CCSD calculation.

mycc = cc.UCCSD(mf_scf)
e_ccsd = mycc.kernel()
dm_ccsd = mycc.make_rdm1()

# Calculate the CCSD density on the grid

rho_ccsd_up = dft.numint.eval_rho(mol, ao, dm_ccsd[0],  None, 'LDA', 0, None)
rho_ccsd_dn = dft.numint.eval_rho(mol, ao, dm_ccsd[1],  None, 'LDA', 0, None)
rho_ccsd = rho_ccsd_up + rho_ccsd_dn

# Save the CCSD density.

np.savetxt('rho_ccsd.dat',rho_ccsd)

# Save the CCSD density on the grid.

cubegen.density(mol, 'rho_ccsd_0.cube', dm_ccsd[0] )
cubegen.density(mol, 'rho_ccsd_1.cube', dm_ccsd[1] )

**Comment by sunqm** [comment]
SCF density matrices are computed in AO basis.  ccsd density matrixes are computed in MO basis. When plotting CCSD density, you need first to transform the ccsd density matrices to AO basis.

**Comment by RandomDefaultUser** [comment]
Thank you for your answer and for including an example how this transformation can be done in cc/01-density_matrix.py! The transformation fixed my problem and now I get the same results as presented in the article.
