### ISSUE TITLE
Incompatible with the latest pyberny 0.3.3

### ISSUE THREAD

**Issue by zwang123** [sunqm/pyscf#223]
Hi,

The author of pyberny (https://github.com/azag0/pyberny) has changed the interface of geomlib. The class Molecule and Crystal were combined to Geometry. So the interface to pyberny in pyscf only supports up to geomlib 0.3.2. Is it possible to update the pyscf code to support the latest version of pyberny?

**Comment by sunqm** [comment]
The new version of pyberny has been considered

https://github.com/sunqm/pyscf/blob/master/pyscf/geomopt/berny_solver.py#L50

This is available in master branch, and dev branch, and the pyscf-1.5.2 on pip.

On Thu, Aug 30, 2018 at 04:54:15PM -0700, zwang123 wrote:
> Hi,
> 
> The author of pyberny (https://github.com/azag0/pyberny) has changed the
> interface of geomlib. The class Molecule and Crystal were combined to Geometry.
> So the interface to pyberny in pyscf only supports up to geomlib 0.3.2. Is it
> possible to update the pyscf code to support the latest version of pyberny?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

-- 
Dr. Qiming Sun
Division of Chemistry and Chemical Engineering
California Institute of Technology
