### ISSUE TITLE
reduce not defined as built-in functions in python3

### ISSUE THREAD

**Issue by MoleOrbitalHybridAnalyst** [sunqm/pyscf#230]
"NameError: name 'reduce' is not defined" when using Python3.

A simple grep shows potentially these files need reduce to be imported from functoolsn for Python3
pyscf/cc/ccsd_rdm.py
pyscf/cc/ccsd_t_rdm_slow.py
pyscf/cc/gccsd_rdm.py
pyscf/cc/gccsd_t_rdm.py
pyscf/cc/rccsd_lambda.py
pyscf/cc/rccsd_slow.py
pyscf/cc/uccsd_rdm.py
pyscf/cc/uccsd_slow.py
pyscf/cc/uccsd_t.py
pyscf/cc/uccsd_t_rdm.py
pyscf/dft/gen_grid.py
pyscf/dft/rks.py
pyscf/future/shciscf/shci.py
pyscf/future/xianci/xianci.py
pyscf/grad/ccsd_slow.py
pyscf/gw/gw.py
pyscf/hci/hci.py
pyscf/hessian/rhf.py
pyscf/hessian/uhf.py
pyscf/lib/cc/ccsd_grad.c
pyscf/lib/diis.py
pyscf/lib/gto/autocode/derivator.cl
pyscf/lib/gto/autocode/gen-code.cl
pyscf/lib/gto/autocode/parser.cl
pyscf/lib/mcscf/fci_contract.c
pyscf/lib/mcscf/select_ci.c
pyscf/lib/mpi/m_mpi.c
pyscf/lib/nao/m_sc_dmatrix.F90
pyscf/lib/np_helper/CMakeLists.txt
pyscf/lib/np_helper/np_helper.h
pyscf/lib/np_helper/omp_reduce.c
pyscf/lib/numpy_helper.py
pyscf/lib/vhf/r_direct_o1.c
pyscf/mcscf/__init__.py
pyscf/mp/gmp2.py
pyscf/mp/ump2.py
pyscf/nao/m_siesta_ion_xml.py
pyscf/nao/test/H.ion.xml
pyscf/nao/test/ice/H.ion.xml
pyscf/nao/test/ice/O.ion.xml
pyscf/nao/test/O.ion.xml
pyscf/pbc/df/incore.py
pyscf/pbc/df/outcore.py
pyscf/pbc/dft/cdft.py
pyscf/pbc/lib/linalg_helper.py
pyscf/pbc/mpicc/kccsd_rhf.py
pyscf/pbc/mpicc/kintermediates_rhf.py
pyscf/pbc/mpitools/mpi.py
pyscf/pbc/mpitools/mpi_helper.py
pyscf/pbc/tools/lattice.py
pyscf/pbc/tools/pbc.py
pyscf/prop/freq/rhf.py
pyscf/shciscf/shci.py
pyscf/symm/geom.py
pyscf/tools/c60struct.py
pyscf/xianci/xianci.py

Sorry for not being very helpful... Really frustrated by Python's scope. Not clear about if there is a simple way to import functools.reduce once and away.

**Comment by sunqm** [comment]
Fixed in latest commit.
