### ISSUE TITLE
Question how the kpts was arranged in pbc library

### ISSUE THREAD

**Issue by bsonghao** [sunqm/pyscf#236]
Hello,

    I was trying to implant something into the pyscf.pbc library,

when i print out the kpts by cell.make_kpts(), it seems that the kpts

has a range of [0,2pi/a) where a is the lattice constant(1d case). 

I wonder how is the k points arranged? According to the solid state theory

the kpts should be within the first Brillouim Zone  which is (-pi/a,pi/a).

Regards

Songhao Bao

**Comment by Jasonmyu** [comment]
If you want the kpts to be chosen within the first brillouin zone, specify the argument "wrap_around" as True in get_kpts()

**Comment by tberkel** [comment]
But to be clear: any two k-points that differ by a reciprocal lattice
vector G are completely equivalent because G\dot a = 2\pi N. Any primitive
cell of the reciprocal lattice is an acceptable choice for k-point
sampling; the first Brillouin zone is only conventional.

**Comment by bsonghao** [comment]
> If you want the kpts to be chosen within the first brillouin zone, specify the argument "wrap_around" as True in get_kpts()
> 
> More information can be found in the documentation:
> https://sunqm.github.io/pyscf/pbc/gto.html

Yeah, it works, thanks.
