### ISSUE TITLE
numint memory usage

### ISSUE THREAD

**Issue by DanSGraham** [sunqm/pyscf#239]
Why is the memory for the numint protocol set to a default value, rather than setting max_memory to the ks.max_memory value? Or barring that, why not set the max_memory to a configurable setting, rather than defaulting it to 2000mb?

**Comment by jdmcclain47** [comment]
It might help to be a little more specific; could you point to the specific file and function in question?  

In general, the dft object's max_memory is passed into the numint.py functions, but I'm noticing that there are a few instances in https://github.com/sunqm/pyscf/blob/master/pyscf/dft/uks.py that forget to do this.  Is this what you are referring to?

For the memory issue, you are able to configure the max_memory - the default is just 2000 mb.  There are many ways to set the max_memory such as in a config file.  The easiest is setting the `mol.max_memory` or `ks.max_memory` (`ks` will just inherit from `mol`).

**Comment by jdmcclain47** [comment]
Ah, nice catch.  I've updated these methods to take in the `ks.max_memory` in the `dev` branch with commit 090d7a77795211ecfcdfc6ced606736fde25d1c7

**Comment by DanSGraham** [comment]
Great! Thanks!
