### ISSUE TITLE
pyscf.fci module missing function "spin_square_with_overlap"

### ISSUE THREAD

**Issue by wirawan0** [sunqm/pyscf#3]
Function `spin_square_with_overlap` was referred to in fci module, in this example file: `examples/mcscf/uhf_casscf.py`. It did not exist in the current version of pyscf.fci .

Thanks,
Wirawan

**Comment by sunqm** [comment]
Hi Wirawan,

Thanks for reporting the bug.  I will fix it in the next version (0.10)

Best,
Qiming

On Mon, Jan 12, 2015 at 11:43:01AM -0800, Wirawan Purwanto wrote:
> Function spin_square_with_overlap was referred to in fci module, in this
> example file: examples/mcscf/uhf_casscf.py. It did not exist in the current
> version of pyscf.fci .
> 
> Thanks,
> Wirawan
> 
> —
> Reply to this email directly or view it on GitHub.*
> 

-- 
Dr. Qiming Sun
Frick Chemistry Laboratory
Princeton University
www.sunqm.net

**Comment by sunqm** [comment]
In the current updates (v0.10), this function has been removed.  It was replaced by mcscf.spin_square function.  The new function can handle both RHF and UHF CASSCF wave functions.
