### ISSUE TITLE
what is gfortran for? 

### ISSUE THREAD

**Issue by ncrubin** [sunqm/pyscf#32]
make demands access to gfortran compiler which is not on the list of dependencies.  Is there a way around this on mac OS X (el cap)?

**Comment by RomitChakraborty** [comment]
Yeah. If you want to install a gfortran compiler that is. Here is the link I used:
<http://hpc.sourceforge.net>

**Comment by gkc1000** [comment]
If you are using a Mac, are you using the clang toolchain rather than gcc?

**Comment by ncrubin** [comment]
The macosx.darwin tool chain (clang set) which does not come with
gfortran.  I've also tried the binaries for gfortran.  Also failed on my
computer.   I have since moved to a linux virtual machine where none of
this is a problem.    I was just curious what gfortran was used for since
it wasn't explicitly listed under the dependencies.

**Comment by sunqm** [comment]
XC functional library libxc requires Fortran compiler.  You can pass it by deleting the corresponding compile script in lib/CMakeLists.txt.  There is a backup library xcfun.  But less functional are defined in xcfun.
