### ISSUE TITLE
oscillator strength

### ISSUE THREAD

**Issue by lucamontana** [sunqm/pyscf#37]
Dear Developers, 

Is it possible to calculate the oscillator strength (dipole matrix elements)
for excited states from DMRG using pyscf ?

Bests
LUCA

**Comment by sunqm** [comment]
There is no function to do the transition dipole.  You can follow this example to calculate the transition dipole    https://github.com/sunqm/pyscf/blob/master/examples/1-advanced/030-transition_dipole.py

For DMRG-based problem,  you'll need modify the transition matrix part in that example.  Note the pyscf-block interface does support the transition dipole matrix for states over different spin/spatial symmetry.  It requires you to collect Block data manually and run an extra Block calculation.  Please refer to   http://sanshar.github.io/Block/examples.html#restart-dmrg-transition-reduced-density-matrix-calculation

Best,
Qiming

https://github.com/sunqm/pyscf/blob/master/examples/1-advanced/030-transition_dipole.py

**Comment by lucamontana** [comment]
Dear Qiming,

I am aware of http://sanshar.github.io/Block/examples.html#restart-dmrg-transition-reduced-density-matrix-calculation, however this seems to me to be the transition between ground and excited state < GS| ES>.
I also need to contract with the position operator :  < GS| r |ES> .
Can you confirm that http://sanshar.github.io/Block/examples.html#restart-dmrg-transition-reduced-density-matrix-calculation is really dipole matrix element calculation ?

I need one particle transition matrix elements contracted **with the position operator**.

Bests
LUCA

**Comment by sunqm** [comment]
state_average_mix function is defined in latest commit.

This line   https://github.com/sunqm/pyscf/blob/master/examples/1-advanced/030-transition_dipole.py#L77
needs to be replaced with DMRG transition matrix.

UKS-TDDFT should be available soon in a few months.  ROKS-TDDFT is not implemented.  I think it might take time to have ROKS-TDDFT because I'm not familiar with its spin-adaptation and some double-excitation problem.

Best,
Qiming

**Comment by sunqm** [comment]
You'll need the transition density matrix from Block code, then contract to
the one-particle dipole integral   mol.intor('cint1e_r_sph', comp=3)

**Comment by lucamontana** [comment]
Ok, assuming i calculated transition matrices using the BLOCK code in a separate folder,  
how can pyscf find the transition densities ? should they be in txt or bin format ?

How should this line : 
t_dm1 = mc.fcisolver.trans_rdm1(ground_state, mc.ci[ci_id], mc.ncas, mc.nelecas)

look like in dmrg based calculation ?

UKS-TDDFT : probably excited states will be then highly spin contaminated.

Best
LUCA

**Comment by lucamontana** [comment]
i successfully manged to install pyscf on my laptop, however have some problems running pyscf on the cluster. I get this error :  

  File "<stdin>", line 1, in <module>
  File "pyscf/__init__.py", line 133, in <module>
    from pyscf import gto
  File "pyscf/gto/__init__.py", line 7, in <module>
    from pyscf.gto import mole
  File "pyscf/gto/mole.py", line 15, in <module>
    import pyscf.lib
  File "pyscf/lib/__init__.py", line 7, in <module>
    from pyscf.lib import linalg_helper
  File "pyscf/lib/linalg_helper.py", line 11, in <module>
    import h5py
ImportError: No module named h5py

any idea how to tell pyscf where h5py is located ?

LUCA

**Comment by lucamontana** [comment]
Try to generate a fcidump file, and end up with this :   

cd    /home/luca/pyscf/examples/tools
python fcidump.py

  File "fcidump.py", line 74, in <module>
    for i in symm.label_orb_symm(mol, mol.irrep_name, mol.symm_orb, c)]
KeyError: 'Dooh'

LUCA

**Comment by sunqm** [comment]
If you computed the transition matrix of same symmetry, this is the function   https://github.com/sunqm/pyscf/blob/master/future/dmrgscf/dmrgci.py#L239   to read Block transition density matrix.  It's defined in mc.fcisolver (assuming you do a DMRG-CASCI calculation) .   For bright state which relates to two irreps, you'll need a little coding based on that function. 

The density matrix of Block code is saved as plain txt file.

**Comment by sunqm** [comment]
The fcidump example is fixed in latest commit.   https://github.com/sunqm/pyscf/blob/master/examples/tools/fcidump.py

**Comment by sunqm** [comment]
for h5py, you need define environment   PYTHONPATH

**Comment by lucamontana** [comment]
Regarding dmrg, I simply shut off the symmetry. I am just interested whether S1 is bright or dark.

I actually use python environment:  
export PYTHONPATH=/home/luca/:/home/luca/h5py-2.5.0/build/lib.linux-x86_64-2.7/h5py$PYTHONPATH

However, h5py still can not be found or is my path to h5py wrong ?

Can i generate a fcidump file using ROHF for openshell molecules ?

LUCA

**Comment by lucamontana** [comment]
I recompiled the code, however i still obtain :
python 030-transition_dipole.py 

Traceback (most recent call last):
File "030-transition_dipole.py", line 32, in 
mc.fcisolver = mcscf.state_average_mix(mc, [solver_ag,solver_b2u], [.5,.5])
AttributeError: 'module' object has no attribute 'state_average_mix' 

LUCA

**Comment by sunqm** [comment]
Here is the function definition https://github.com/sunqm/pyscf/blob/master/mcscf/addons.py#L634

Did you  git clone the repo  or download the 1.1-release?  This function is not available in 1.1.

/home/luca/h5py-2.5.0/build/lib.linux-x86_64-2.7/h5py  is not the right path.   You might need run
    python setup.py install --prefix=/path/to/your/python/lib/dir
in  /home/luca/h5py-2.5.0

Qiming

**Comment by lucamontana** [comment]
I git cloned. I can see the function definition : https://github.com/sunqm/pyscf/blob/master/mcscf/addons.py#L634

However still get the error. Somehow the definition can not be found.

LUCA

**Comment by lucamontana** [comment]
How can i tell pyscf to generate a FCIDUMP for specific number of orbitals ?
I am looking for predefined active space for which i like to have the FCIDUMP file. 

LUCA

**Comment by sunqm** [comment]
You can transform the integrals with a set of orbital and pass the transformed integrals to fcidump function, eg   https://github.com/sunqm/pyscf/blob/master/examples/tools/fcidump.py#L33

**Comment by lucamontana** [comment]
How can i transform the integrals with a set of orbitals ? any example input ?
The code tales per default all orbitals. Have no clue how to change it.

**Comment by lucamontana** [comment]
Try to run  15-state_average.py  and get :

Traceback (most recent call last):
  File "15-state_average.py", line 31, in <module>
    mc = mcscf.CASSCF(mf, 4, 4).state_average_([.64,.36]).run(verbose=4)
AttributeError: 'CASSCF' object has no attribute 'state_average_'

**Comment by sunqm** [comment]
For 1 electron integral, you can call mol.intor function to get the AO integrals, then two numpy.dot to multiply orbitals from left and right side.  For 2 electron integrals, eg   https://github.com/sunqm/pyscf/blob/master/examples/ao2mo/00-mo_integrals.py

wrt the AttributeError, probably your branch is not on the main branch.  Maybe you have an old pyscf clone somewhere and your PYTHONPATH points to there

**Comment by lucamontana** [comment]
That's fine, but how to SET number of orbitals ?  
In molpro you do this by frozen and occ cards, are there any thing similar keywords in pyscf ?

How can i increase or decrease number of orbitals in this eg. :  ?
https://github.com/sunqm/pyscf/blob/master/examples/ao2mo/00-mo_integrals.py

**Comment by sunqm** [comment]
In that example, orb is a numpy array. eg  orb[:,2:4] are the 3rd, and 4th orbitals

**Comment by lucamontana** [comment]
Ok, i accordingly tried to change the input file below,  if i increase the number of orbitals, 
it runs, however it always generates FCIDUMP file for 24 orbitals, no matter what you set.

If i decrease the number of orbitals (lower than 24) , i get an assertion error.

#!/usr/bin/env python
#
# Author: Qiming Sun <osirpt.sun@gmail.com>
#

from functools import reduce
import numpy
from pyscf import gto, scf, ao2mo
from pyscf import tools
from pyscf import symm

'''
Write FCIDUMP file
'''

mol = gto.M(
    atom = '''N    .000000     .000000     .141690
H            .000000     .806442    -.495913
H            .000000    -.806442    -.495913  ''',
#    basis = 'aug-ccpvtz',
    basis = 'def2-svp',
    verbose = 0,
    spin=1,
    symmetry = 1,
    symmetry_subgroup = 'c2v',
)


myhf = scf.density_fit(scf.ROHF(mol))
energy = myhf.kernel()
print('E = %.12f, ref = -76.0259362997' % energy)

myhf.auxbasis = 'def2-svp-fit'

#myhf.analyze()

c = myhf.mo_coeff

#
# FCIDUMP for given 1e and 2e integrals
#

h1e = reduce(numpy.dot, (c.T, myhf.get_hcore(), c[:,0:24]))
eri = ao2mo.kernel(mol, c[:,0:24])

tools.fcidump.from_integrals('fcidump.example1', h1e, eri, c.shape[1],
                             mol.nelectron, ms=1)

#
# Bypass small matrix elements in FCIDUMP
#
tools.fcidump.from_integrals('fcidump.example2', h1e, eri, c.shape[1],
                             mol.nelectron, ms=1, tol=1e-10)

#
# Inculde the symmetry information in FCIDUMP
#
# to write the irreps for each orbital, first use pyscf.symm.label_orb_symm to
# get the irrep ids
MOLPRO_ID = {'D2h': { 'Ag' : 1,
                      'B1g': 4,
                      'B2g': 6,
                      'B3g': 7,
                      'Au' : 8,
                      'B1u': 5,
                      'B2u': 3,
                      'B3u': 2},
             'C2v': { 'A1' : 1,
                      'A2' : 4,
                      'B1' : 2,
                      'B2' : 3},
             'C2h': { 'Ag' : 1,
                      'Bg' : 4,
                      'Au' : 2,
                      'Bu' : 3},
             'D2' : { 'A ' : 1,
                      'B1' : 4,
                      'B2' : 3,
                      'B3' : 2},
             'Cs' : { "A'" : 1,
                      'A"' : 2},
             'C2' : { 'A'  : 1,
                      'B'  : 2},
             'Ci' : { 'Ag' : 1,
                      'Au' : 2},
             'C1' : { 'A'  : 1,}}

orbsym = [MOLPRO_ID[mol.groupname][i]
          for i in symm.label_orb_symm(mol, mol.irrep_name, mol.symm_orb, c)]
tools.fcidump.from_integrals('fcidump.example3', h1e, eri, c.shape[1],
                             mol.nelectron, ms=1, orbsym=orbsym)

**Comment by sunqm** [comment]
c_sub = myhf.mo_coeff[:,:5]
h1e = reduce(numpy.dot, (c_sub.T, myhf.get_hcore(), c_sub))
eri = ao2mo.kernel(mol, c_sub)
tools.fcidump.from_integrals('fcidump.example1', h1e, eri, c.shape[1], mol.nelectron, ms=1)

**Comment by lucamontana** [comment]
ok, i can now change number of orbitals how i want.
I am now trying to change the number of electrons, however i obtain :   

Traceback (most recent call last):
  File "fcidump.py", line 54, in <module>
    h1e = reduce(numpy.dot, (c_sub.T, myhf.get_hcore(), c_sub))
ValueError: matrices are not aligned

For electrons i used this :
c_sub = myhf.mo_coeff[2:9,:11]

**Comment by lucamontana** [comment]
I compiled qcint  library https://github.com/sunqm/qcint  however, don't know how to link to
pyscf at compilation time, or pyscf is automatically linked against qcint ?

**Comment by lucamontana** [comment]
When run pyscf on a large molecule for scf , i see that it runs for a while on just one single processor
and after that suddenly it runs on multi cores. How do you explain this ?

**Comment by gkc1000** [comment]
Changing the number of electrons does not involve changing the MO coefficients, as the FCIDUMP integrals don't depend on the number of electrons. In 

tools.fcidump.from_integrals('fcidump.example1', h1e, eri, c.shape[1], mol.nelectron, ms=1)

simply change mol.nelectron in the argument, to write a different number of electrons to the FCIDUMP file.

Regarding the number of cores used: as with all programs that use threads, at certain parts of the code threads are spawned and multiple cores are used, and in other parts of the code a single thread is used. 

As the current discussion does not raise an issue with pyscf, I am marking the issue closed. Please open another issue if you have further issues.
