### ISSUE TITLE
Process for update

### ISSUE THREAD

**Issue by jl2922** [sunqm/pyscf#42]
We pull the newest version but seems it still output 16 digits. Do we need to recompile and make the build folder even if it is some change with a python file?

**Comment by gkc1000** [comment]
No - should work! If you put it in a new directory, you need to update your PYTHONPATH.

**Comment by jl2922** [comment]
Seems there is something wrong with my changes. I will check it and let you know.

**Comment by jl2922** [comment]
Ah, I forgot to pass the floating number format to the sub functions it calls.

**Comment by jl2922** [comment]
Fixed in https://github.com/sunqm/pyscf/pull/43
