### ISSUE TITLE
Increasing precision on scf calculations

### ISSUE THREAD

**Issue by RomitChakraborty** [sunqm/pyscf#44]
I'm trying to increase the precision of scf (and later fullCI) calculations. On going through the manual I see that pyscf.tools.dump_mat.dump_rec accepts as a kwarg digits of precision.
Is there a simple way to increase digits of precision in class definition for the molecule?

**Comment by sunqm** [comment]
dump_mat.dump_rec only affects the precision in output format.  If you want to get more accurate SCF or FCI solution, you can set .tol attributes for each module.  eg

mol = ..
mf = scf.RHF(mol)
mf.tol = 1e-15    # default is 1e-9
mf.kernel()

ci = fci.FCI(mol, mf.mo_coeff)
ci.tol = 1e-15   # default is 1e-10
ci.kernel()

mc = mcscf.CASSCF(mf, norb, nelec)
mc.fcisolver.tol = 1e-15   # default is 1e-10
mc.tol = 1e-8    # default is 1e-7
mc.kernel()

**Comment by RomitChakraborty** [comment]
Thanks Qiming!
