### ISSUE TITLE
PBC /  Integrals

### ISSUE THREAD

**Issue by TApplencourt** [sunqm/pyscf#55]
Hi, 

First I would like to congratulate you first this well documented project! He his really easy to use.
Secondly, I'm a fresh new in the solide-world so please excuse me is I ask some silly questions.

Here is my problem:
- I was not able to compute the Coulomb type integral  using the  density fitting technique to avoid the divergent integrals.  I was wondering if you could help me finding some example who is doing that. Indeed http://sunqm.github.io/pyscf/pbc/gto.html lead to http://sunqm.github.io/pyscf/pbc/tools.html#pbc-df but I don't thing this is related to my problem.

Thank you a lot! 

Thomas

PS : I need to rotate those integrals in the MO basis set and I didn't find a function to do it. So I wrote a small one. I hope it is correct and that it can be useful to you too:

```python
def ao_mo_mono(mo_coeff,l_k_int)
    """Rotate the mono-electronic integrals from the ao-basis to the mo-basis

    Keyword arguments:
     - mo_coeff [dimension: (mo_num,ao_num)] -- the rotation matrix coefficient
     - l_k_int     [dimension: (k_pts, ao_num, ao_num)] -- For each k_pts the value of the integral concerned of the AO basis set.

    Return:
     - [dimension: (k_pts, mo_num, mo_num)] -- For each k_pts the value of the integral concerned
of the MO basis set.

    """
   return [ reduce(numpy.dot, (mo_coeff.T, l_int, mo_coeff)) for l_int in l_k_int ]
```

**Comment by sunqm** [comment]
Here are two examples for 2-electron integrals for PBC systems
https://github.com/sunqm/pyscf/blob/master/examples/pbc/30-ao_integrals.py
https://github.com/sunqm/pyscf/blob/master/examples/pbc/30-mo_integrals.py

In your 1-particle integral transformation code,  you might need consider the possibility that mo_coeff are complex and orbitals are different for different k-points.

Qiming

**Comment by TApplencourt** [comment]
Thank you for the example [0] and the tips!

[0] FYI: The 30-ao-integrals example didn't compile. (no `SCF` module is imported, and `itools` didn't exist). To help avoid this kind of issue,  you can use a  continuous integration service like [Travis CI](https://travis-ci.org/). It's free and really easy to deploy.
