### ISSUE TITLE
A question about 2-center 2-electrons integral in density fitting module.

### ISSUE THREAD

**Issue by chenxin199261** [sunqm/pyscf#67]
I am reading the density fitting code, I am confusing with the comment and manual. 
2-center 2-electron AO integrals (L|ij).
I think these integrals should be notated as (K|L) K and L belonging to auxiliary basis.

```
def fill_2c2e(mol, auxmol, intor='cint2c2e_sph', comp=1, hermi=1, out=None):
    '''2-center 2-electron AO integrals (L|ij), where L is the auxiliary basis.
    '''
    return auxmol.intor(intor, comp=comp, hermi=hermi, out=out)
```

**Comment by sunqm** [comment]
You're correct.  It's fixed in latest commit.
