### ISSUE TITLE
Running test_ccsd_t.py with nosetests hangs

### ISSUE THREAD

**Issue by mjw99** [sunqm/pyscf#71]
Seeing this with 1.3.1. When running nosetests in pyscf-1.3.1/cc/test, this hangs on the test_ccsd_t.py test, but if I run the test explicitly, it works:
```
pyscf-1.3.1/cc/test$ export PYTHONPATH=../..

$ nosetests -v
test_ccsd (test_2e.KnowValues) ... ok
test_ccsd (test_bz.KnowValues) ... ok
test_ccsd (test_ccsd_lambda.KnowValues) ... ok
....HANG...

$ python test_ccsd_t.py 
converged SCF energy = -76.02676567312
E(CCSD) = -76.24010890731908  E_corr = -0.2133432341990576
Full Tests for CCSD(T)
CCSD(T) correction = -8.49533879364604
.CCSD(T) correction = -0.00306002261051893
CCSD(T) correction = -0.00306002261051893

----------------------------------------------------------------------
Ran 4 tests in 0.297s

OK
```

**Comment by sunqm** [comment]
It may be a bug of nosetests.  I reported the problem to the nose develop team, see https://github.com/nose-devs/nose/issues/1048

**Comment by mjw99** [comment]
Many thanks for the information and additional bug report. Out of interest, how do you invoke your unit tests locally to work around this issue?

**Comment by sunqm** [comment]
I just call python test_ccsd_t.py in the command line.
