### ISSUE TITLE
FindBLAS.cmake fails to find openblas

### ISSUE THREAD

**Issue by yurivict** [sunqm/pyscf#84]
```
CMake Error at /usr/local/share/cmake/Modules/FindBLAS.cmake:684 (message):
  A required library with BLAS API not found.  Please specify library
  location.
```

I have openblas-0.2.19 installed that provides /usr/local/lib/libopenblas.so
Intel MKL isn't available for my platform (FreeBSD).

**Comment by sunqm** [comment]
I'm not sure whether FindBLAS module supports openblas.  A simple solution is to specify the path in pyscf/lib/CMakeLists.txt
https://github.com/sunqm/pyscf/blob/master/lib/CMakeLists.txt#L36

**Comment by yurivict** [comment]
This works, thanks!
