### ISSUE TITLE
Symmetry SCF calculation with completely fixed irrep_nelec fails

### ISSUE THREAD

**Issue by wirawan0** [sunqm/pyscf#9]
Qiming,

I found that SCF calculation with symmetry (hf_symm.RHF, for example) may fail if all the electrons are fixed using irrep_nelec facility. (Does this even make sense, at all?) Below is a testcase:

    """C atom, cc-pVDZ basis, with symmetry
    At equilibrium (r(C-C)=1.25 angstroms).
    """
    
    from pyscf import gto
    from pyscf import scf
    
    mol = gto.Mole()
    mol.build(
        verbose = 5,
        #output = 'rhf_c2_symm.outx',
    #   Coordinates are in Angstrom
        atom = [
          ['C' , (0. , 0. , 0.625)],
          ['C' , (0. , 0. ,-0.625)],
        ],
        basis = {'C': 'cc-pVDZ',},
        spin = 0,
    # mute argument parsing and input file dumping (WP)
        parse_arg = True, dump_input = True,
        symmetry = True,
    )
    # For more details, see pyscf/gto/mole.py
    
    print "RHF calculation"
    rhf = scf.hf_symm.RHF(mol)
    rhf.conv_threshold = 1e-8
    rhf.irrep_nelec = {'Ag': 4, 'B1u': 4, 'B2u': 2, 'B3u': 2,}
    #rhf.chkfile = "rhf_c2_symm.chk"
    #print('E=%.15g' % rhf.scf(dump_chk=False))
    print('E=%.15g' % scf.hf.kernel(rhf, dump_chk=False))

It fails with "UnboundLocalError: local variable 'elumo_float' referenced before assignment" message. Here's the traceback:

    Traceback (most recent call last):
      File "C2_RHF_nelec_bug.py", line 31, in <module>
        print('E=%.15g' % scf.hf.kernel(rhf, dump_chk=False))
      File "/home/wirawan/Work/python-lib/pyscf/scf/hf.py", line 93, in kernel
        mo_occ = mf.get_occ(mo_energy, mo_coeff)
      File "/home/wirawan/Work/python-lib/pyscf/scf/hf_symm.py", line 219, in get_occ
        nocc = int((mo_energy[p0:p0+nso]<elumo_float).sum())

I think this should be easy to fix, but I don't know what elumo_float to use if we don't have free electrons.

Wirawan

**Comment by sunqm** [comment]
Thanks for reporting this bug.  It's fixed in the latest version (0.10)
